import { CardType } from '../components/card';
import { UncalculatedBaseCard } from './base-cards';
import { BaseCardType, Rarity } from './enums';
import { Element } from './enums';

export const brokenPair: UncalculatedBaseCard[] = [
  {
    set: 3,
    name: 'Seeker',
    filename: 'seeker',
    id: 140,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 5,
    pips: [Element.Earth],
    hp: 3,
    power: 4,
    speed: 2,
    text: '(Combat): When this card enters play, search your deck for an Epic Card, reveal it and put it into your hand. Shuffle.\n (Combat): While you control a (Combat) King, this Card gains the subtype Knight.',
    ccc: 4,
    artist: 'A. Z. Volt',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Annihilate',
    filename: 'annihilate',
    id: 141,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 6,
    pips: [Element.Dark, Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: '(Stack): Pay (2) less to play this Card if it is played as your action.\n Destroy all (Combat) Units.',
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Alpha - Bred for War',
    filename: 'alphabredforwar',
    id: 142,
    epic: 'Alpha',
    supertype: BaseCardType.Unit,
    subtype: ['Cat'],
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 4,
    power: 1,
    speed: 3,
    text: '(Combat): Swiftstrike 2.\n(Combat): While you control another (Combat), this Card gains +1 Spd.',
    ccc: 0,
    artist: 'Gabriel Rearte',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Fire) >= 0;
    },
  },
  {
    set: 3,
    name: 'Aspirant Craftsman',
    filename: 'aspirantcraftsman',
    id: 143,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Warrior'],
    cost: 1,
    pips: [Element.Water],
    hp: 1,
    power: 1,
    speed: 1,
    text: '(Combat): When this Card enters play, deal 1 damage to target (C) Unit.\n(Dead): (Water) (Water): Place this Card into your resource zone exhausted.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Abolisher',
    filename: 'abolisher',
    id: 144,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Knight'],
    cost: 7,
    pips: [Element.Earth, Element.Earth, Element.Earth],
    hp: 5,
    power: 7,
    speed: 2,
    text: '(Combat): This Card cannot be Dazed.\n(Combat): At end of turn, destroy all (Combat) Enemy Continuous Events.',
    ccc: 1,
    artist: 'Robert Nix',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Abyss Initiate',
    filename: 'abyssinitiate',
    id: 145,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 3,
    pips: [Element.Dark],
    hp: 2,
    power: 3,
    speed: 2,
    text: '(Combat): When this Card enters play, place an "Assassin\'s Honor" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Amplifier',
    filename: 'amplifier',
    id: 146,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Craftsman'],
    cost: 3,
    pips: [Element.Water],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(Combat): Increase non-combat damage done by Water Cards you control by 1.',
    ccc: 3,
    artist: 'Wellington Viana',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Avarisa Darkhart - Student of Magic',
    filename: 'avarisadarkhartstudentofmagic',
    id: 147,
    epic: 'Avarisa Darkhart',
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 1,
    pips: [Element.Dark, Element.Dark, Element.Dark],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): When you resolve a Dark Event, Surge 1. If that Event has Pwr 3 or 4, draw a Card instead. If that Event has Pwr 5 or greater, take five additional actions instead.',
    ccc: 3,
    artist: 'Ray of Sand',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Army Initiate',
    filename: 'armyinitiate',
    id: 148,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 2,
    pips: [Element.Fire],
    hp: 1,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, place a "Soldier\'s Consignment" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Battle Lead',
    filename: 'battlelead',
    id: 149,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Soldier'],
    cost: 3,
    pips: [Element.Light],
    hp: 4,
    power: 3,
    speed: 2,
    text: '(Combat): You may Link an additional Item to this Card.\n(Combat): For each Item Linked to this Card, it gains +1 Spd.',
    ccc: 3,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Berserker',
    filename: 'berserker',
    id: 150,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Barbarian'],
    cost: 3,
    pips: [Element.Air],
    hp: 2,
    power: 2,
    speed: 3,
    text: "(Combat): Once per turn; (1), Discard a Card: Deal damage equal to this Card's Pwr to target (Combat) Unit.",
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Contact a Leyline',
    filename: 'contactaleyline',
    id: 151,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 3,
    text: "Choose one:\n - Negate target (Stack) Event if it has cost 3 or less.\n - Destroy target (Combat) Continuous Event if it has cost 3 or less.\n - Shuffle up to 3 target (Dead) Cards into their owners' decks.",
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Counterpoint',
    filename: 'counterpoint',
    id: 152,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Light],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Lightbound: Deal damage equal to this Card's HP to target (Combat) Unit if a (Combat) Structure you control was attacked this turn.\nAirbound: Draw a Card.\n(Stack): Firebound: +2HP.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Bert - Trench Boss',
    filename: 'berttrenchboss',
    id: 153,
    epic: 'Bert',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Mercenary', 'Soldier'],
    cost: 3,
    pips: [Element.Water],
    hp: 4,
    power: 4,
    speed: 2,
    text: "(Combat): Evasion 1.\n(Combat): Sworn Enemy (Fire): +1 Spd.\n(Combat): At start of turn, return target (Resource) Card you control to its owner's hand.",
    ccc: 3,
    artist: 'Robert Nix',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Blind',
    filename: 'blind',
    id: 154,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Dark],
    hp: 0,
    power: 2,
    speed: 0,
    text: 'Daze target (Combat) Unit. (A Dazed Unit has its Spd set to 0 until end of turn.)',
    ccc: 5,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Cavalier',
    filename: 'cavalier',
    id: 155,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Knight'],
    cost: 3,
    pips: [Element.Earth, Element.Earth],
    hp: 5,
    power: 1,
    speed: 1,
    text: '(Combat): Armor 1.\n(Combat): While Linked with "Aegis Spear," "Armmentia," "Heavy Lance," "Javelin," or "Light Lance," this Card gains + 3Pwr.',
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Clandestine Dealings',
    filename: 'clandestinedealings',
    id: 156,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Dark],
    hp: 0,
    power: 1,
    speed: 0,
    text: "Move target (Dead) Dark Card you own to the top of your deck. If that Card's cost is less than this Card's Pwr, draw a Card.",
    ccc: 5,
    artist: 'Jeansil Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Call Storm',
    filename: 'callstorm',
    id: 157,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 4,
    pips: [Element.Air, Element.Air],
    hp: 0,
    power: 2,
    speed: 3,
    text: "Deal damage equal to this Card's Pwr to target (Combat) Unit. Do this a number of times equal to this Card's Spd.",
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Water) >= 0;
    },
  },
  {
    set: 3,
    name: 'Cat Attack',
    filename: 'catattack',
    id: 158,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Place two "War Kitten" Tokens into your combat zone.',
    ccc: 6,
    artist: 'Jeansil Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Dame Chaeri - Blade Dancer',
    filename: 'damechaeribladedancer',
    id: 159,
    epic: 'Dame Chaeri',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Barbarian', 'Soldier'],
    cost: 4,
    pips: [Element.Fire, Element.Air, Element.Light],
    hp: 4,
    power: 2,
    speed: 4,
    text: '(Combat): Once per Action; (1), Discard a Card: Until end of action, this Card gains Swiftstrike 2 for each damage on in, or Armor equal to its Pwr, or Pwr equal to its Spd.',
    ccc: 2,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Light) >= 0;
    },
  },
  {
    set: 3,
    name: 'Disenchanter',
    filename: 'disenchanter',
    id: 160,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Craftsman'],
    cost: 2,
    pips: [Element.Water, Element.Water],
    hp: 3,
    power: 2,
    speed: 2,
    text: "(Combat): When this card enters play, you may move target (Combat) Item to the bottom of its owner's deck.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Eager Recruit',
    filename: 'eagerrecruit',
    id: 161,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 3,
    pips: [Element.Fire, Element.Fire, Element.Earth],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(Combat): While this Card is recovered, you must choose attack as your action.\n(Combat): Earthbound: This Card gains the Subtype Knight.',
    ccc: 4,
    artist: 'Marcelo Salaza',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Elder Barbarian',
    filename: 'elderbarbarian',
    id: 162,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Barbarian'],
    cost: 4,
    pips: [Element.Air],
    hp: 5,
    power: 2,
    speed: 2,
    text: '(Combat): Once per turn; 1, Discard a Card: This Card gains +2 Pwr until end of turn.\n(Combat): When you discard a Card, heal 1 damage from this Card.',
    ccc: 1,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Empower',
    filename: 'empower',
    id: 163,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Target (Combat) Unit gains +1 Spd and +1 Pwr until end of turn. Move any number of target (Dead) "Spark" Cards you own to the bottom of your deck. For each Card moved, that Unit gains +1 Spd and +1 Pwr until end of turn.',
    ccc: 2,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Entry Specialist',
    filename: 'entryspecialist',
    id: 164,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Tactician'],
    cost: 5,
    pips: [Element.Dark, Element.Dark],
    hp: 5,
    power: 4,
    speed: 2,
    text: '(Combat): When this Card deals combat damage to an Enemy Shrine, take an additional action.',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Eternal Flame Militant',
    filename: 'eternalflamemilitant',
    id: 165,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Soldier'],
    cost: 3,
    pips: [Element.Fire, Element.Fire, Element.Fire],
    hp: 4,
    power: 2,
    speed: 1,
    text: '(Combat): While damaged, this Card gains Armor 2 and +2 Pwr.\n(Combat): When this Card destroys a (Combat) Unit with an attack, heal all damage from this Card.',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Eternal Flame Oath',
    filename: 'eternalflameoath',
    id: 166,
    epic: null,
    supertype: BaseCardType.ContinuousEvent,
    subtype: [],
    cost: 1,
    pips: [Element.Fire],
    hp: 1,
    power: 0,
    speed: 1,
    text: '(Combat): All damaged (Combat) Units you control gain Armor 1. (Armor decreases any damage received by 1.)',
    ccc: 3,
    artist: 'Jeansil Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Faceless Abyss',
    filename: 'facelessabyss',
    id: 167,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Assassin'],
    cost: 3,
    pips: [Element.Dark, Element.Dark, Element.Water],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(Stack): Waterbound: This Card cannot be negated.\n(Combat): When this Card enters play, if it was played as the first action of the turn, you may destroy target (Combat) Unit.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Falconer',
    filename: 'falconer',
    id: 168,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Ranger'],
    cost: 3,
    pips: [Element.Earth],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(Combat): At end of turn, destroy target (Combat) Unit if it is a Token.\n(Combat): All (Combat) Rangers you control gain Sworn Enemy Cat +2 Spd.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'For the Eternal Flame',
    filename: 'fortheeternalflame',
    id: 169,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Choose one:\n - Deal 1 damage to target (Combat) Unit you control.\n - All (Dead) Cards cannot move from a (Dead) zone until end of turn.\n - Recover target (Combat) Unit if it destroyed a (Combat) Unit with an attack this turn.',
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Frontier Scout',
    filename: 'frontierscout',
    id: 170,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Ranger'],
    cost: 2,
    pips: [Element.Earth, Element.Earth],
    hp: 2,
    power: 2,
    speed: 1,
    text: '(Combat): When this card enters play, you may place a card from your hand into your resource zone exhausted.',
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: "Griffin's Arms Bearer",
    filename: 'griffin_sarmsbearer',
    id: 171,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 3,
    pips: [Element.Earth],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, return target (Dead) Earth Item you own to your hand.\n(Combat): While you control a (Combat) King, this Card gains the subtype Knight.',
    ccc: 4,
    artist: 'Anthony Filipe',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Griffin IV - Balancing',
    filename: 'griffinivbalancing',
    id: 172,
    epic: 'Griffin IV',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'King'],
    cost: 4,
    pips: [Element.Earth],
    hp: 5,
    power: 3,
    speed: 2,
    text: '(Combat): When this Card enters play, return target (Dead) Earth Item you own to your hand.\n(Combat): While Linked with an Item, this Card gains Armor 1, Evasion 1, Ruin, and +1 Pwr. If the Linked Item is "X," double these values.',
    ccc: 4,
    artist: 'Lee Sands',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Guard Headquarters',
    filename: 'guardheadquarters',
    id: 173,
    epic: null,
    supertype: BaseCardType.Structure,
    subtype: [],
    cost: 6,
    pips: [Element.Light, Element.Light, Element.Light],
    hp: 6,
    power: 3,
    speed: 1,
    text: '(Combat): Regenerate 2.\nThis Card may defend as if it were a Unit.',
    ccc: 2,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Highwayman',
    filename: 'highwayman',
    id: 174,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Ranger', 'Tactician'],
    cost: 3,
    pips: [Element.Earth, Element.Dark],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(Resource): You may play this Card.',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Hinterland Thane',
    filename: 'hinterlandthane',
    id: 175,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Knight'],
    cost: 4,
    pips: [Element.Earth, Element.Earth],
    hp: 4,
    power: 3,
    speed: 2,
    text: '(Combat): When this Card enters play, place the top Card of your deck into your resource zone exhausted.\n(Combat): Earthbound: When this Card is destroyed, place it into your resource zone exhausted.',
    ccc: 3,
    artist: 'Matias Novoa',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Huntress',
    filename: 'huntress',
    id: 176,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Ranger'],
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 2,
    power: 1,
    speed: 3,
    text: '(Combat): Stealth 1.\n(Combat): While you control another (Combat) Cat, this Card gains Swiftstrike 2.\n(Combat): When this Card enters play, place a "War Kitten" Token into your combat zone.',
    ccc: 3,
    artist: 'Jeansill Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Hydrokinetic Strike',
    filename: 'hydrokineticstrike',
    id: 177,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 1,
    text: 'Destroy target (Combat) Unit if it is damaged.',
    ccc: 2,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Infiltrator',
    filename: 'infiltrator',
    id: 178,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 2,
    pips: [Element.Water],
    hp: 2,
    power: 2,
    speed: 3,
    text: "(Combat): Stealth 1.\n(Combat): When this Card deals combat damage to an Enemy Shrine, return this Card to its owner's hand. All your future actions this turn must be pass.",
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Javelin',
    filename: 'javelin',
    id: 179,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 1,
    pips: [Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Unit you control.\n(Combat): Linked Unit gains +1 Spd.\n(Combat): Linked Unit gains Swiftstrike 1. (Swiftstrike increases damage by 1 while in combat with a Unit with less Spd.)\n(Combat): Destroy this Card: Deal 1 damage to target (Combat) Unit.',
    ccc: 5,
    artist: 'Wellington Viana',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Khet - Wild Matriarch',
    filename: 'khetwildmatriarch',
    id: 180,
    epic: 'Khet',
    supertype: BaseCardType.Unit,
    subtype: ['Cat', 'Queen'],
    cost: 5,
    pips: [Element.Earth, Element.Light, Element.Fire],
    hp: 1,
    power: 5,
    speed: 1,
    text: '(Combat): Armor 5.\n(Combat): When this Card is destroyed, place five "War Kitten" Tokens into your combat zone.',
    ccc: 3,
    artist: 'Valeria Karasu',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Kill',
    filename: 'kill',
    id: 181,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Destroy target (Combat) Unit if it has the lowest Pwr among (Combat) Units.\n(Stack): Accuracy.',
    ccc: 6,
    artist: 'Giraz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Kiralla - War Torn',
    filename: 'kirallawartorn',
    id: 182,
    epic: 'Kiralla',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Warrior'],
    cost: 6,
    pips: [Element.Air, Element.Air],
    hp: 5,
    power: 2,
    speed: 1,
    text: '(Combat): For each (Combat) Dazed Enemy Unit, this Card gains +2 Pwr.\n(Combat): At end of turn, destroy all (Combat) Dazed Enemy Units.',
    ccc: 3,
    artist: 'Untung Forever',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Kite Shield',
    filename: 'kiteshield',
    id: 183,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 2,
    pips: [Element.Earth],
    hp: 3,
    power: 0,
    speed: 1,
    text: 'Links to a (Combat) Unit you control.\n(Combat): Linked Unit gains Armor 1.\n(Combat): Linked Unit cannot be Dazed.\n(Combat): Destroy this Card: Linked Unit cannot take damage until end of Action.',
    ccc: 2,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Knight Captain',
    filename: 'knightcaptain',
    id: 184,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Knight'],
    cost: 4,
    pips: [Element.Earth, Element.Earth],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): All (Combat) Knights you control gain Accuracy.',
    ccc: 4,
    artist: 'Gabriel Rearte',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Leona - Big Sister',
    filename: 'leonabigsister',
    id: 185,
    epic: 'Leona',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Princess'],
    cost: 7,
    pips: [Element.Dark, Element.Fire, Element.Earth],
    hp: 8,
    power: 4,
    speed: 2,
    text: '(Combat): When this Card enters play, return target (Dead) Card you own to your hand. If that Card is a Knight with cost 4 or less, move it to your combat zone instead.\n(Combat): When this Card destroys a (Combat) Unit with an attack, Surge ∞.',
    ccc: 6,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Lightning Fast Fencer',
    filename: 'lightningfastfencer',
    id: 186,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Warrior'],
    cost: 2,
    pips: [Element.Air, Element.Light],
    hp: 2,
    power: 1,
    speed: 3,
    text: '(Combat): Swiftstrike 3. (Swiftstrike increases damage by 3 while in combat with a Unit with less Spd.)',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Masked Invader',
    filename: 'maskedinvader',
    id: 187,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Tactician'],
    cost: 2,
    pips: [Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): Stealth 2.\n(Combat): When this Card deals combat damage to an Enemy Shrine, all (Stack) non-Continuous Dark Events you control gain +1 Pwr until end of turn.',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Mark of the Pits',
    filename: 'markofthepits',
    id: 188,
    epic: null,
    supertype: BaseCardType.ContinuousEvent,
    subtype: [],
    cost: 2,
    pips: [Element.Fire],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Links to a (Combat) damaged Unit.\n(Combat): Linked Unit gains this Card's HP, +1 Pwr, Accuracy, and Swiftstrike 2.",
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Novice Strategist',
    filename: 'novicestrategist',
    id: 189,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Mercenary'],
    cost: 1,
    pips: [Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): -5 Initiative.\n While you control another (Combat) Tactician, this Card gains +8 Initiative.',
    ccc: 4,
    artist: 'Marcelo Salaza',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Nomadic Militia',
    filename: 'nomadicmilitia',
    id: 190,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 1,
    pips: [],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): For each (Combat) Item you control, this Card gains +1 Spd and +1 Pwr.',
    ccc: 1,
    artist: 'Jeansil Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Master Falconer',
    filename: 'masterfalconer',
    id: 191,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Barbarian', 'Ranger'],
    cost: 3,
    pips: [Element.Air],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(Combat): Once per turn; (1), Discard a Card: Destroy all (Combat) Token Units.',
    ccc: 4,
    artist: 'Reeve',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Minor Hydrokinetics',
    filename: 'minorhydrokinetics',
    id: 192,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Deal 1 damage to target (Combat) Unit.\n(Dead): When a (Combat) Craftsman enters play under your control, return this Card to its owner's hand.",
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Mercenary Captain',
    filename: 'mercenarycaptain',
    id: 193,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Mercenary'],
    cost: 3,
    pips: [Element.Dark, Element.Dark],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(Combat): All (Combat) Mercenaries you control gain +2 Initiative.',
    ccc: 6,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Mountain Totem',
    filename: 'mountaintotem',
    id: 194,
    epic: null,
    supertype: BaseCardType.Structure,
    subtype: [],
    cost: 2,
    pips: [Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): (Exhaust): Target (Combat) Barbarian gains +1 Pwr until end of turn.\n(Combat): When you discard a Card, recover this Card.',
    ccc: 3,
    artist: 'Anthonny Filipe',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Old Man Gerhalt - Avenger',
    filename: 'oldmangerhaltavenger',
    id: 195,
    epic: 'Old Man Gerhalt',
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Cleric', 'Craftsman'],
    cost: 6,
    pips: [Element.Light, Element.Water, Element.Air],
    hp: 6,
    power: 3,
    speed: 3,
    text: '(Combat): When this card enters play, you may daze target (Combat) Unit.\nOnce per turn; (Light) (Water): Move any amount of damage from target (Combat) Shrine you control to this card, if you do, deal that much damage to target (Combat) Unit.',
    ccc: 3,
    artist: 'Matias Novoa',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Order Initiate',
    filename: 'orderinitiate',
    id: 196,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 1,
    pips: [Element.Earth],
    hp: 2,
    power: 1,
    speed: 1,
    text: 'When this card enters play, place a "Knight\'s Oath" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'Matias Novoa',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: "Osa'Ra - Master Assassin",
    filename: 'osa_ramasterassassin',
    id: 197,
    epic: "Osa'Ra",
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Assassin'],
    cost: 4,
    pips: [Element.Air, Element.Dark, Element.Water],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(Combat): Stealth 3.\nWhen you play an Event, you may deal 1 damage to target (Combat) Unit.\n(Combat): When you resolve a "Throat Cut," return it to its owner\'s hand.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Outsider',
    filename: 'outsider',
    id: 198,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Soldier'],
    cost: 2,
    pips: [Element.Light],
    hp: 4,
    power: 1,
    speed: 2,
    text: '(Combat): For each damage on this Card, it gains +1 Pwr.',
    ccc: 4,
    artist: 'Jeansil Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Rawl - Broken Pair',
    filename: 'rawlbrokenpair',
    id: 199,
    epic: 'Rawl',
    supertype: BaseCardType.Unit,
    subtype: [],
    cost: 7,
    pips: [Element.Water, Element.Earth, Element.Dark],
    hp: 7,
    power: 7,
    speed: 3,
    text: '(Combat): Accuracy.\nWhen this Card enters play, each opponent takes an additional action, then you take an additional action. After these actions, the turn ends.\n(Combat): While attacking a (Combat) Unit, this Card gains Stealth ∞.',
    ccc: 2,
    artist: 'Kyle Petchock',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Reclamation',
    filename: 'reclamation',
    id: 200,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 3,
    pips: [Element.Earth, Element.Dark],
    hp: 0,
    power: 0,
    speed: 1,
    text: 'Return target (Dead) Card or (Resource) Card you own to your hand.',
    ccc: 6,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Retreat',
    filename: 'retreat',
    id: 201,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 1,
    text: "Return target (Combat) Unit you control to its owner's hand.",
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Riverbed Patrol',
    filename: 'riverbedpatrol',
    id: 202,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Barbarian', 'Craftsman'],
    cost: 3,
    pips: [Element.Water, Element.Water, Element.Air],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(Combat): When you discard a card for the first time each turn, you may deal 1 damage to target Unit.\n(Combat): Once per turn; (1), Discard a Card: Draw a Card.',
    ccc: 3,
    artist: 'Matias Novoa',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Run Down',
    filename: 'rundown',
    id: 203,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Deal damage equal to this Card's Pwr plus the number of Knights you control to target (Combat) Unit.",
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => true,
  },
  {
    set: 3,
    name: 'Shield Breaker',
    filename: 'shieldbreaker',
    id: 204,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 2,
    pips: [Element.Earth, Element.Earth],
    hp: 3,
    power: 2,
    speed: 0,
    text: "Links to a (Combat) Unit you control.\n(Combat): Linked Unit gains this Card's Pwr.\n(Combat): Destroy this Card: Destroy target (Combat) Item or (Combat) Continuous Event.",
    ccc: 2,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Steam Powered Blast',
    filename: 'steampoweredblast',
    id: 205,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 6,
    pips: [Element.Water, Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: '(Stack): Pay 2 less to play this Card if it was played as your action. Destroy target (Combat) non-Shrine Card.',
    ccc: 3,
    artist: 'Matias Novoa',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: "Stranger's Initiate",
    filename: 'stranger_sinitiate',
    id: 206,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 3,
    pips: [Element.Light],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, place a "Cleric\'s Pledge" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Snatch',
    filename: 'snatch',
    id: 207,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Dark, Element.Dark],
    hp: 0,
    power: 0,
    speed: 3,
    text: 'Each opponent chooses a (Combat) Unit they control and destroys it.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Smithy',
    filename: 'smithy',
    id: 208,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 2,
    pips: [Element.Light, Element.Light],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(Combat): (Exhaust): Target (Combat) Unit gains Armor 1 until end of turn. If that Unit is Linked with an Item, it gains Armor 2 until end of turn instead.',
    ccc: 6,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Stray',
    filename: 'stray',
    id: 209,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Cat'],
    cost: 2,
    pips: [Element.Fire, Element.Earth],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): Armor 1.\n(Combat): Swiftstrike 1.\n(Combat): This Card cannot be Dazed.',
    ccc: 3,
    artist: 'Matias Novoa',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Smash',
    filename: 'smash',
    id: 210,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 3,
    pips: [Element.Fire, Element.Earth],
    hp: 0,
    power: 2,
    speed: 0,
    text: "Choose one:\n - Destroy target (Combat) Item.\n - Destroy target (Combat) Continuous Event.\n - Deal damage equal to this Card's Pwr to target (Combat) Structure.",
    ccc: 2,
    artist: 'Valeria Karasu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Shook',
    filename: 'shook',
    id: 211,
    epic: null,
    supertype: BaseCardType.ContinuousEvent,
    subtype: [],
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Unit. (Combat): When this Card enters play, Daze Linked Unit.\n(Combat): At start of turn, Daze Linked Unit.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Spark',
    filename: 'spark',
    id: 212,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 1,
    pips: [Element.Air],
    hp: 0,
    power: 2,
    speed: 0,
    text: "Deal damage equal to this Card's Pwr to target (Combat) Unit.",
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Summit Enforcer',
    filename: 'summitenforcer',
    id: 213,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Soldier'],
    cost: 5,
    pips: [Element.Fire],
    hp: 5,
    power: 5,
    speed: 2,
    text: '(Combat): While you control a (Combat) "War Cat Summit," this Card gains Steadfast. (Defends without exhausting.)',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Szofh - Terror Beheld',
    filename: 'szofhterrorbeheld',
    id: 214,
    epic: 'Szofh',
    supertype: BaseCardType.Unit,
    subtype: ['Assassin'],
    cost: 2,
    pips: [Element.Dark, Element.Dark],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(Combat): (Dark), (Exhaust): Daze target (Combat) Unit if it has cost 4 or less.',
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Temple Elder',
    filename: 'templeelder',
    id: 215,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Warrior'],
    cost: 2,
    pips: [Element.Air],
    hp: 2,
    power: 3,
    speed: 0,
    text: '(Combat): Sworn Enemy Dazed Unit: Lethal.\n(Combat): Sworn Enemy Knight: +1 Pwr and +1 Spd.',
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Temple Initiate',
    filename: 'templeinitiate',
    id: 216,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 6,
    pips: [Element.Air],
    hp: 4,
    power: 6,
    speed: 0,
    text: '(Combat): When this Card enters play, place a "Warrior\'s Vow" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Throat Cut',
    filename: 'throatcut',
    id: 217,
    epic: null,
    supertype: BaseCardType.Event,
    subtype: [],
    cost: 2,
    pips: [Element.Dark],
    hp: 0,
    power: 2,
    speed: 0,
    text: "Destroy target (Combat) Unit if its Spd is less than this Card's Pwr.\n(Stack): If played as the first action of the turn, this Card gains +1 Pwr.",
    ccc: 5,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Totem Gorge - Meeting House',
    filename: 'totemgorgemeetinghouse',
    id: 218,
    epic: 'Totem Gorge',
    supertype: BaseCardType.Structure,
    subtype: [],
    cost: 2,
    pips: [Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): At start of turn, each player draws a Card.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Touch of The Abyss',
    filename: 'touchoftheabyss',
    id: 219,
    epic: null,
    supertype: BaseCardType.ContinuousEvent,
    subtype: [],
    cost: 3,
    pips: [Element.Dark],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Links to a (Combat) Unit.\n(Combat): Linked Unit gains this Card's Spd.\n(Combat): Linked Unit gains Lethal. (A Lethal Card's combat damage immediately destroys Units.)\n(Combat): Linked Unit gains Ruin.\n(A Ruin Card's damage destroys any non-Shrine Structure at end of turn.)",
    ccc: 5,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Trench Captain',
    filename: 'trenchcaptain',
    id: 220,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Soldier'],
    cost: 4,
    pips: [Element.Water, Element.Water],
    hp: 5,
    power: 2,
    speed: 2,
    text: '(Combat): Sworn Enemy Fire: +1 Spd.\n(Combat): (Exhaust): Return another target (Combat) non-Shrine Card you own to your hand.',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Trench Infantry',
    filename: 'trenchinfantry',
    id: 221,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Soldier'],
    cost: 2,
    pips: [Element.Water],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): Sworn Enemy Fire: +1 Spd. (This Card gains the added text while in combat with a Unit of the listed variety.)\n(Combat): When a (Combat) Card or (Resource) Card is returned to your hand, recover this Card and it gains +1 Pwr until end of turn.',
    ccc: 4,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Unknown Source',
    filename: 'unknownsource',
    id: 222,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 1,
    pips: [Element.Dark],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): All (Combat) Assassins, Mercenaries and Tacticians you control gain +1 Initiative.\n(Combat): All (Stack) non-Continuous Dark Events you control gain +1 Pwr.',
    ccc: 2,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Wandering Spearman',
    filename: 'wanderingspearman',
    id: 223,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Cleric', 'Soldier'],
    cost: 4,
    pips: [Element.Light, Element.Light],
    hp: 5,
    power: 1,
    speed: 3,
    text: '(Combat): Steadfast. (Defends without exhausting.)\n(Combat): Regenerate 1. (Heal 1 damage from this Card at the end of each turn.)\n(Combat): For each damage on this Card, it gains +1 Pwr.',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: "Wanderer's Garb",
    filename: 'wanderer_sgarb',
    id: 224,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 2,
    pips: [Element.Light],
    hp: 3,
    power: 0,
    speed: 5,
    text: "Links to a (Combat) Unit.\n(Combat): Linked Unit gains this Card's HP.",
    ccc: 5,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Zweihander',
    filename: 'zweihander',
    id: 225,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 2,
    pips: [Element.Fire],
    hp: 2,
    power: 2,
    speed: 5,
    text: "Links to a (Combat) Unit you control.\n(Combat): Linked Unit gains Accuracy until end of turn.\n(Combat): When Linked Unit destroys a (Combat) Unit with an attack, you may deal damage equal to this Card's Pwr to target (Combat) Unit.",
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Yawatara Initiate',
    filename: 'yawatarainitiate',
    id: 226,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human'],
    cost: 5,
    pips: [Element.Water],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): When this Card enters play, place a "Craftsman\'s Word" Token into your combat zone Linked to this Card.',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Weapon Rack',
    filename: 'weaponrack',
    id: 227,
    epic: null,
    supertype: BaseCardType.Item,
    subtype: [],
    cost: 1,
    pips: [Element.Light],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Structure.\n(Combat): Linked Structure gains +1 Pwr.\n(Combat): (Exhaust): Move target (Combat) Item you own from one (Combat) Unit to another.',
    ccc: 6,
    artist: 'Allain Paul Canlas',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Trouble Shooter',
    filename: 'troubleshooter',
    id: 228,
    epic: null,
    supertype: BaseCardType.Unit,
    subtype: ['Human', 'Ranger'],
    cost: 3,
    pips: [Element.Dark, Element.Dark],
    hp: 3,
    power: 3,
    speed: 3,
    text: "(Combat): When you resolve a Dark Event, this Card gains Swiftstrike equal to that Event's Pwr until end of turn.\n(Combat): Darkbound: Ruin.",
    ccc: 1,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'Yawatara Training',
    filename: 'yawataratraining',
    id: 229,
    epic: null,
    supertype: BaseCardType.ContinuousEvent,
    subtype: [],
    cost: 4,
    pips: [Element.Water, Element.Water],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(Combat): All (Combat) Units you control gain +1 to their keyword abilities.\n(Combat): Use this ability once per turn; (1): Pay 2 less for the next Event you play this turn if it is played as your action.',
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    set: 3,
    name: 'War Cat Summit - Breeding Grounds',
    filename: 'warcatsummitbreedinggrounds',
    id: 230,
    epic: 'War Cat Summit',
    supertype: BaseCardType.Structure,
    subtype: [],
    cost: 3,
    pips: [Element.Fire],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): (Fire), (Exhaust): Place a "War Kitten" Token into your combat zone.',
    ccc: 2,
    artist: 'Kateryna Vitkovska',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
];
