enum CardType {
  Unit,
  Event,
  ContinuousEvent,
  Item,
  Structure,
}

export enum Element {
  Air,
  Dark,
  Earth,
  Fire,
  Light,
  Water,
  Neutral,
}

enum Rarity {
  Common,
  Uncommon,
  Rare,
  Epic,
}
class BaseCard {
  name: string;
  filename: string;
  epic: boolean;
  supertype: CardType;
  subtype: string;
  cost: Element[];
  hp: number;
  power: number;
  speed: number;
  text: string;
  ccc: number;
  artist: string;
  rarity: Rarity;
}

let base_cards: BaseCard[] = [
  {
    name: 'Absorb Magic',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Earth, Element.Earth],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Negate target (S) Event.',
    ccc: 2,
    artist: 'J.C. Grande',
    rarity: Rarity.Common,
  },
  {
    name: 'Aegis Greenhorn',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Earth],
    hp: 3,
    power: 2,
    speed: 1,
    text: '(C): While defending, this Card gains Armor 1. (Armor decreases any damage received by 1.)',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Alleyway Intimidator',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Mercenary',
    cost: [Element.Neutral, Element.Dark],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(C): While attacking a (C) Shrine you control, Units have their Stealth value decreased by 1. (C): Any player may use this ability; (5): Destroy target (C) Unit if it has Stealth.',
    ccc: 3,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Common,
  },
  {
    name: 'Armentia - Celestial Spear',
    filename: '',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Light, Element.Light],
    hp: 0,
    power: 0,
    speed: 5,
    text: 'Links to a (C) Unit. (C): Linked Unit gains +1 Spd. (C): Linked Unit gains "When this Card deals combat damage to a Unit, Daze that Unit." (C): If Linked Unit is Light, it gains Accuracy.',
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
  },
  {
    name: 'Arsonist',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Dark, Element.Fire],
    hp: 4,
    power: 2,
    speed: 2,
    text: "(C): Darkbound: +1 Pwr. (C): Firebound: +2 Initiative. (C): When this Card enters play, if it was played as the first action of the turn, deal damage equal to this Card's Pwr to target (C) Structure.",
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
  },
  {
    name: 'Avarisa Darkhart - Silver Tongued',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Dark, Element.Dark],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): Your first action each turn counts as the first action of the turn.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
  },
  {
    name: 'Backstab',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark, Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, destroy target (C) Unit. If you control a (C) Assassin, draw a Card.',
    ccc: 6,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
  },
  {
    name: 'Banishment',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Light],
    hp: 4,
    power: 0,
    speed: 2,
    text: "Negate target (S) Unit if its Pwr is less than this Card's HP. (S): While you control a (C) Cleric, this Card gains +1 HP.",
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
  },
  {
    name: 'Barracks',
    filename: '',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Fire],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(C): All (C) Fire Units you control gain +1 Pwr. (C): (↻): Target (C) Soldier gains +1 Spd until end of turn.',
    ccc: 6,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Common,
  },
  {
    name: 'Battlefield Headsman',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Fire, Element.Fire],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): When a (C) Enemy Unit is destroyed for the first time each turn, recover this Card.',
    ccc: 1,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
  },
  {
    name: 'Best Laid Plans',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Light],
    hp: 3,
    power: 0,
    speed: 0,
    text: "Take a number of additional actions equal to this Card's HP. After these actions, all your future actions this turn must be pass.",
    ccc: 1,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Binding Chains',
    filename: '',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Fire, Element.Fire],
    hp: 2,
    power: 1,
    speed: 0,
    text: "Links to an exhausted (C) Unit. (C): Linked Unit does not recover at the start of each turn. (C): At end of turn, deal damage equal to this Card's Pwr to Linked Unit.",
    ccc: 2,
    artist: 'Guillermo Villarreal',
    rarity: Rarity.Common,
  },
  {
    name: 'Bladeborne Dreng',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Fire, Element.Neutral, Element.Water],
    hp: 1,
    power: 3,
    speed: 2,
    text: '(C): When this Card enters play, deal 1 damage to target (C) Unit or (C) Structure.',
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
  },
  {
    name: 'Blue Back Strategist',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Water, Element.Water, Element.Neutral],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): Stealth 1. (C): Waterbound: All (C) Units you control with Stealth cannot be attacked.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Brute',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Barbarian',
    cost: [Element.Neutral, Element.Water],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(C): At end of turn, discard a Card.',
    ccc: 4,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Common,
  },
  {
    name: 'Burst of Speed',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Target (C) Unit gains this Card's Spd and Swiftstrike 2 until end of action.",
    ccc: 2,
    artist: 'Rafael Lenhellas',
    rarity: Rarity.Common,
  },
  {
    name: 'Bury Magic',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Place target (C) Continuous Event or (C) Item into its controller's resource zone exhausted.",
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Call Lightning',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Air],
    hp: 0,
    power: 2,
    speed: 1,
    text: "Deal damage equal to this Card's Pwr to target (C) Unit. (S): Airbound: +1 Pwr. (This Card gains the added text if its Essence is Air.)",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Call Wind',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Air, Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Exhaust target (C) Unit. Airbound: Exhaust target (C) Unit. You may discard a Card, if you do, exhaust target (C) Unit.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
  },
  {
    name: 'Careful Sneak',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Water],
    hp: 2,
    power: 2,
    speed: 1,
    text: '(C): Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Churn',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Return target (R) Card you own to your hand. Draw a Card. Place a Card from your hand into your resource zone exhausted.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Rare,
  },
  {
    name: 'Cleanse',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Light],
    hp: 0,
    power: 0,
    speed: 3,
    text: 'Destroy target (C) Continuous Event.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Combat Medic',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Light],
    hp: 2,
    power: 0,
    speed: 0,
    text: '(C): (3): Heal damage equal to this Card’s HP from another target (C) Unit.',
    ccc: 1,
    artist: 'Lee Sands',
    rarity: Rarity.Common,
  },
  {
    name: 'Conjure Barrier',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Water],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Target (C) Shrine cannot take damage until end of turn. All your future actions this turn must be pass.',
    ccc: 2,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Counter Assassin',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Assassin',
    cost: [Element.Dark, Element.Dark],
    hp: 2,
    power: 3,
    speed: 2,
    text: '(C): When this Card enters play, you may destroy target (C) Unit if it has Stealth.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Rare,
  },
  {
    name: 'Covert Operation',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Target (C) Unit gains Stealth 2 until end of turn. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.) Darkbound: Draw a Card. (This Card gains the added text if its Essence is Dark)',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Cutthroat',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Assassin',
    cost: [Element.Dark, Element.Dark],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): Stealth 1. (C): Darkbound: +1 Spd and +1 Pwr. (C): When this Card enters play, you may destroy target (C) Unit if its Spd is less than this Card’s Pwr.',
    ccc: 2,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
  },
  {
    name: 'Demolition Vanguard',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Water, Element.Water],
    hp: 2,
    power: 4,
    speed: 2,
    text: 'Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)\nThis Card may only attack Structures.',
    ccc: 1,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Devoted Defender',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Light],
    hp: 6,
    power: 2,
    speed: 2,
    text: 'While defending, this Card gains +2Spd and +2Pwr.',
    ccc: 3,
    artist: 'Lee Sands',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Disbelief',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Water, 'Water', Element.Water],
    hp: 0,
    power: 0,
    speed: 2,
    text: "Move target non-Shrine Epic Card to the bottom of its owner's deck.",
    ccc: 0,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
  },
  {
    name: 'Disgraced Veteran',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Dark, Element.Fire],
    hp: 2,
    power: 3,
    speed: 1,
    text: "Lethal. (A Lethal Card's combat damage immediately destroys Units.)",
    ccc: 1,
    artist: 'Kayla Raney',
    rarity: Rarity.Rare,
  },
  {
    name: 'Distrust',
    filename: '',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Water, Element.Earth],
    hp: 1,
    power: 0,
    speed: 3,
    text: 'When this Card enters play, negate target Event unless its controller pays 2.\nWhen an opponent targets one of your Cards, place this Card into your resource zone exhausted.',
    ccc: 0,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Epic,
  },
  {
    name: "D'Marque Heirloom - Gilded Mask",
    filename: '',
    epic: true,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Water, Element.Water],
    hp: 3,
    power: 0,
    speed: 5,
    text: 'Links to a Human you control.\nLinked Unit gains the Subtype Queen.\nWhen Linked Unit would be destroyed for the first time each turn, you may destroy another Human you control instead, if you do, heal all damage from Linked Unit.',
    ccc: 1,
    artist: 'Arte Express Studio',
    rarity: Rarity.Epic,
  },
  {
    name: 'Driis Palisade',
    filename: '',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Earth],
    hp: 4,
    power: 0,
    speed: 1,
    text: 'All Shrines you control cannot be attacked.',
    ccc: 1,
    artist: 'Megan Toole',
    rarity: Rarity.Epic,
  },
  {
    name: 'Driis Sentry',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Ranger',
    cost: [Element.Earth],
    hp: 3,
    power: 3,
    speed: 2,
    text: 'All Earth Structures you control gain Armor 1.',
    ccc: 2,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
  },
  {
    name: 'Drown',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Water],
    hp: 0,
    power: 0,
    speed: 4,
    text: "Destroy target Unit if its Pwr is less than this Card's Spd.",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
  },
  {
    name: 'Dying Breath',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Fire],
    hp: 0,
    power: 1,
    speed: 0,
    text: 'Recover target Unit you control. It gains this Card’s Pwr until end of turn. At end of turn, destroy it.',
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
  },
  {
    name: 'Earthquake',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Deal 3 damage to all Structures. Earthbound: Exhaust all Units if their Pwr is less than the number of Cards you control.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
  },
  {
    name: 'Earth’s Elite',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Earth, Element.Earth],
    hp: 4,
    power: 4,
    speed: 2,
    text: 'Armor 1. (Armor decreases any damage received by 1.)',
    ccc: 1,
    artist: 'Robert Nix',
    rarity: Rarity.Rare,
  },
  {
    name: 'Elvyra - Slayer Squad Commander',
    filename: '',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Fire, Element.Fire],
    hp: 3,
    power: 2,
    speed: 2,
    text: 'All Fire Units you control gain +1Pwr. When this Card deals combat damage to an Enemy Shrine, recover another target Fire Unit you control.',
    ccc: 2,
    artist: 'Giraaz Studio',
    rarity: Rarity.Epic,
  },
  {
    name: 'Eternal Flame Soldier',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Soldier',
    cost: [Element.Fire],
    hp: 6,
    power: 3,
    speed: 2,
    text: 'Regenerate 1. (Heal 1 damage from this Card at end of turn.)',
    ccc: 4,
    artist: 'Robert Nix',
    rarity: Rarity.Rare,
  },
  {
    name: 'Expert Combatant',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Earth],
    hp: 2,
    power: 5,
    speed: 2,
    text: 'Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 2,
    artist: 'Untung Forevers',
    rarity: Rarity.Rare,
  },
  {
    name: 'Exploit Might',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark, Element.Dark],
    hp: 0,
    power: 4,
    speed: 0,
    text: 'For each Unit you control with Stealth, this Card gains -1Pwr. Destroy target non-Epic Unit if its Pwr is greater than this Card’s Pwr.',
    ccc: 6,
    artist: 'Giraaz Studio',
    rarity: Rarity.Epic,
  },
  {
    name: 'Fablemonger',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Earth, Element.Light],
    hp: 4,
    power: 4,
    speed: 1,
    text: 'Lightbound: Regenerate 1. Earthbound: When this Card is destroyed, place it into your resource zone exhausted.',
    ccc: 2,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Rare,
  },
  {
    name: 'Fierce Protector',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Earth, 'Earth', Element.Earth],
    hp: 5,
    power: 5,
    speed: 2,
    text: 'Steadfast. When you play an Earth Card, heal 1 damage from target Shrine. When you Surge, increase the Surge value by 1.',
    ccc: 2,
    artist: 'J. C. Grande',
    rarity: Rarity.Rare,
  },
  {
    name: "Fighter's Heart",
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: 'Continuous Event',
    cost: [Element.Air],
    hp: 1,
    power: 1,
    speed: 0,
    text: 'Links to a Unit. Linked Unit gains this Card’s Pwr. If Linked Unit is Air, it gains Steadfast.',
    ccc: 1,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
  },
  {
    name: 'Finishing Move',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Fire, Element.Fire],
    hp: 0,
    power: 2,
    speed: 4,
    text: 'Negate target Card. If that Card has cost 3 or less, deal damage equal to this Card’s Pwr to target Shrine controlled by the same player as the negated Card.',
    ccc: 2,
    artist: 'Robert Nix',
    rarity: Rarity.Epic,
  },
  {
    name: 'Firebomb',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Deal 1 damage to all Units and all Structures.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
  },
  {
    name: 'Fire Palm Strike',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Fire],
    hp: 0,
    power: 2,
    speed: 1,
    text: 'Target Unit gains this Card’s Pwr until end of turn.',
    ccc: 3,
    artist: 'Vicar Tochi',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'First Strike',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, destroy target Unit if it has cost 2 or less. Otherwise, destroy target Unit if it has cost 1 or less.',
    ccc: 3,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Epic,
  },
  {
    name: 'Fountain of Life',
    filename: '',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Water, Element.Light],
    hp: 8,
    power: 0,
    speed: 0,
    text: 'Exhaust a Unit: Move any amount of damage from that Unit to this Card.',
    ccc: 2,
    artist: 'Kateryna Vitkovska',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Funeral Pyre',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: 'Continuous Event',
    cost: [Element.Fire],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'All Dark Cards lose all abilities. All Dark Cards cannot be targeted.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
  },
  {
    name: 'Gale Warrior',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Fire, Element.Air],
    hp: 3,
    power: 2,
    speed: 2,
    text: 'Airbound: +1Spd and +1Pwr. Firebound: +1Spd and +1Pwr.',
    ccc: 3,
    artist: 'Robert Nix',
    rarity: Rarity.Epic,
  },
  {
    name: 'Garrison',
    filename: '',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Light],
    hp: 1,
    power: 0,
    speed: 5,
    text: 'Links to a Structure. Linked Structure may defend as if it were a Unit.',
    ccc: 6,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
  },
  {
    name: 'Griffin IV - Earth Splitter',
    filename: '',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human King',
    cost: [Element.Earth, Element.Earth],
    hp: 7,
    power: 0,
    speed: 2,
    text: 'This Card gains Pwr equal to the number of R Cards you control.\nEarthbound: When this Card is destroyed, place it into your resource zone exhausted.',
    ccc: 6,
    artist: 'Kayla Raney',
    rarity: Rarity.Epic,
  },
  {
    name: 'Grizzled Crop Keeper',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Earth],
    hp: 4,
    power: 0,
    speed: 0,
    text: 'Surge 2. (Recover up to 2 R Cards you control.)\nR: R',
    ccc: 6,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Common,
  },
  {
    name: 'Grunt',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Fire],
    hp: 2,
    power: 2,
    speed: 2,
    text: '',
    ccc: 3,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
  },
  {
    name: 'Guardian of The Sacred Grove',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Earth],
    hp: 6,
    power: 1,
    speed: 1,
    text: 'Steadfast. (Defends without exhausting.)',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
  },
  {
    name: 'Guard Shack',
    filename: '',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Light],
    hp: 4,
    power: 1,
    speed: 1,
    text: 'This Card may defend as if it were a Unit.',
    ccc: 2,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Common,
  },
  {
    name: 'Gust',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Return target non-Shrine Card to its owner's hand.\nAccuracy. (Events with Accuracy ignore Evasion.)",
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Hatred',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark, Element.Fire],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Destroy target Unit if it is Light, Water or Earth.',
    ccc: 2,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Heat Stroke',
    filename: '',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Fire, Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Links to a Unit.\nAt end of turn, Linked Unit's controller discards a Card or destroys Linked Unit.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Highland Isolationist',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: 'While you control no other Units, this Card gains +1Spd, +2Pwr and +3HP.',
    ccc: 4,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
  },
  {
    name: 'Holy Symbol',
    filename: '',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Light, Element.Water],
    hp: 1,
    power: 0,
    speed: 5,
    text: [
      'Links to a Unit.',
      'Linked Unit cannot be targeted by Fire, Air or Dark Cards.',
      'If Linked Unit is a Cleric, it gains this Card’s HP.',
    ],
    ccc: 3,
    artist: 'Francisco K. Pérez Ortiz',
    rarity: Rarity.Rare,
  },
  {
    name: 'Hurricane',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Air, Element.Air],
    hp: 0,
    power: 1,
    speed: 0,
    text: [
      'Deal damage equal to this Card’s Pwr to all Units.',
      'Airbound: +1Pwr.',
    ],
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Icy Skin',
    filename: '',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Water, Element.Dark],
    hp: 5,
    power: 0,
    speed: 1,
    text: [
      'Links to a Human.',
      "Linked Unit gains 'This Card only takes combat damage from Fire Units.'",
    ],
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Intelligence Operative',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Dark],
    hp: 4,
    power: 1,
    speed: 1,
    text: [
      'Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)',
      '+2 Initiative.',
    ],
    ccc: 3,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
  },
  {
    name: 'Invisible Force',
    filename: '',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Air, Element.Dark],
    hp: 0,
    power: 4,
    speed: 0,
    text: [
      'Return target Enemy Unit to its owner’s hand. If that Unit has less Pwr than this Card, draw a Card.',
    ],
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Knife Expert',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Assassin Tactician',
    cost: [Element.Dark, Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: [
      'Stealth 1.',
      'When this Card attacks as the first action of the turn, take an additional action that counts as the first action of the turn.',
    ],
    ccc: 2,
    artist: 'Kayla Raney',
    rarity: Rarity.Epic,
  },
  {
    name: 'Life Cycle Warden',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Water, 'Dark', Element.Earth],
    hp: 5,
    power: 4,
    speed: 2,
    text: [
      'When this Card enters play, return target Card you own to your hand.',
    ],
    ccc: 4,
    artist: 'Robert Nix',
    rarity: Rarity.Common,
  },
  {
    name: 'Light Lance',
    filename: '',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Earth, Element.Earth],
    hp: 1,
    power: 0,
    speed: 5,
    text: [
      'Links to a Unit.',
      'Linked Unit gains Accuracy. (Attackers with Accuracy may attack recovered Units.)',
      'If Linked Unit is a Knight, it gains +1Spd.',
    ],
    ccc: 6,
    artist: 'J. C. Grande',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Lightning Warrior',
    filename: '',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Air, 'Air', Element.Air],
    hp: 4,
    power: 3,
    speed: 2,
    text: [
      'When this Card enters play, you may Daze target Unit.',
      "1 , : Move target 'Call Lightning' you own to the bottom of your deck, if you do, deal damage equal to this Card’s Pwr to target Unit.",
    ],
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
  },
  {
    name: 'Little Breeze - A New Way',
    filename: 'littlebreezeanewway',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human Shaman',
    cost: [Element.Neutral, Element.Air, Element.Air],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(C): When this Card enters play, draw a Card.\n(C): Airbound: When this Card enters play, draw a Card.\n(C)(1), Discard a Card: Exhaust target (C) Unit.',
    ccc: 2,
    artist: 'Chris Jones',
    rarity: Rarity.Epic,
  },
  {
    name: 'Lowland Hunter',
    filename: 'lowlandhunter',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Ranger Soldier',
    cost: [Element.Neutral, Element.Earth, Element.Light],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): Accuracy. (Attackers with Accuracy may attack recovered Units.)\n(C): Sworn Enemy (D): +4Spd. (This Card gains the added text while in combat with a Unit of the listed variety.)',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Melee Alumnus',
    filename: 'meleealumnus',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Neutral, Element.Fire, Element.Fire],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(C): Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 1,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
  },
  {
    name: 'Mend',
    filename: 'mend',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Light, Element.Light],
    hp: 5,
    power: 0,
    speed: 0,
    text: "Heal damage equal to this Card's HP from target (C) Card.",
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Might of the Earth',
    filename: 'mightoftheearth',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Neutral, Element.Earth, Element.Earth],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (C) Earth Unit.\n(C): Linked Unit gains Pwr equal to the number of (R) Earth Cards you control.',
    ccc: 6,
    artist: 'Lee Sands',
    rarity: Rarity.Common,
  },
  {
    name: 'Mikiri Frontliner',
    filename: 'mikirifrontliner',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Neutral, Element.Fire, Element.Fire],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(C): Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
  },
  {
    name: 'Natural Forces',
    filename: 'naturalforces',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Water, Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Place target (C) Unit into its controller's resource zone exhausted, if you do, that player returns another (R) Card they own to their hand.",
    ccc: 2,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
  },
  {
    name: "Nature's Divinity",
    filename: 'naturesdivinity',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Neutral, Element.Earth, Element.Light],
    hp: 2,
    power: 0,
    speed: 0,
    text: 'Links to a (C) Unit or (C) Structure.\n(C): If Linked Card is Light, it gains Regenerate 2.\n(C): If Linked Card is Earth, it gains Armor 1.',
    ccc: 2,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Night Watch',
    filename: 'nightwatch',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Light],
    hp: 4,
    power: 2,
    speed: 1,
    text: '(C): While you control a (C) Structure that may defend as if it were a Unit, this Card gains +1Spd and +1Pwr.',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Novice Sellsword',
    filename: 'novicesellsword',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Mercenary',
    cost: [Element.Neutral, Element.Dark],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(C): -5 Initiative.',
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
  },
  {
    name: 'Nullifier',
    filename: 'nullifier',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Knight',
    cost: [Element.Neutral, Element.Earth, Element.Earth, Element.Earth],
    hp: 4,
    power: 4,
    speed: 1,
    text: '(C): Earthbound: At end of turn, each opponent destroys a (C) Continuous Event they control.',
    ccc: 2,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Common,
  },
  {
    name: 'Old Man Gerhalt - Trinity Speaker',
    filename: 'oldmangerhalttrinityspeaker',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Neutral, Element.Light, Element.Water, Element.Earth],
    hp: 3,
    power: 3,
    speed: 3,
    text: "(C): When this Card enters play, heal damage equal to this Card's HP from target (C) Shrine.\n(C): Lightbound: +3HP.\n(C): Waterbound: +3Pwr.\n(C): Earthbound: When this Card is destroyed, place it into your resource zone exhausted.",
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
  },
  {
    name: 'Partisan',
    filename: 'partisan',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Water],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(C): Stealth 2. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Payday',
    filename: 'payday',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If you control a (C) Assassin, draw a Card. If you control a (C) Tactician, draw a Card. If all (C) Enemy Structures are damaged, draw a Card.',
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
  },
  {
    name: 'Pillory',
    filename: 'pillory',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Neutral, Element.Dark],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(C): (Turn) : Target (C) Unit cannot attack this turn.',
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Pincer Maneuver',
    filename: 'pincermaneuver',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'All (C) Units you control with Stealth gain Evasion 1 until end of turn.\n(D): When a Unit you control with Stealth deals combat damage to an Enemy Shrine for the first time each turn, you may deal 1 damage to target (C) Unit.',
    ccc: 4,
    artist: 'Omari Perez',
    rarity: Rarity.Common,
  },
  {
    name: 'Planting',
    filename: 'planting',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Place the top Card of your deck into your resource zone exhausted.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Prayers Answered',
    filename: 'prayersanswered',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Light, Element.Light],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Move any amount of damage from (C) Units you control to (C) Structures you control.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Quarterstaff',
    filename: 'quarterstaff',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Neutral, Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (C) Unit you control.\n(C): If Linked Unit is Air, it gains +1Spd.\n(C): (Element.Neutral)(Element.Neutral), Exhaust Linked Unit: Daze target (C) Unit. (A Dazed Unit has its Spd set to 0 until end of turn.)',
    ccc: 6,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Common,
  },
  {
    name: 'Quicksilver Wings - Mystic Headpiece',
    filename: 'quicksilverwingsmysticheadpiece',
    epic: true,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Neutral, Element.Air, Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: 'Links to a (C) Unit.\n(C): Linked Unit gains this Card\'s Spd.\n(C): If Linked Unit is Air, it gains "When you discard a Card, recover this Card."\n(C)(1), Discard a Card: Return another target (C) Item or (C) Continuous Event to its owner\'s hand.',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Epic,
  },
  {
    name: 'Ram the Gates',
    filename: 'ramthegates',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Fire],
    hp: 0,
    power: 2,
    speed: 0,
    text: "Deal damage equal to this Card's Pwr to target (C) Structure.",
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Re-equip',
    filename: 're-equip',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Light],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Return target (D) Item to its owner's hand.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
  },
  {
    name: 'Refugee',
    filename: 'refugee',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Light],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(C): While you control a (C) non-Shrine Light Structure, this Card gains +1HP.',
    ccc: 4,
    artist: 'Francisco K. Pérez Ortiz',
    rarity: Rarity.Common,
  },
  {
    name: 'Root Tender',
    filename: 'roottender',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Earth],
    hp: 2,
    power: 2,
    speed: 1,
    text: '(C): When this Card enters play, heal 2 damage from target (C) Structure.\n(C): When this Card enters play, heal 2 damage from target (C) "The Great Oak."',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Royal Custodian',
    filename: 'royalcustodian',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Neutral, Element.Water, Element.Water],
    hp: 4,
    power: 3,
    speed: 2,
    text: '(C): Evasion 2. (Opponents must pay an additional (2) to target this Card.)',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
  },
  {
    name: "Ruebane - Fury's Avatar",
    filename: 'ruebanefurysavatar',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Warrior',
    cost: [Element.Neutral, Element.Dark, Element.Fire, Element.Air],
    hp: 4,
    power: 3,
    speed: 3,
    text: "(C): When this Card enters play, if it was played as the first action of the turn, deal damage equal to this Card's Pwr to target (C) Shrine.\n(C): (Element.Fire)(Element.Fire): This Card gains Accuracy until end of turn.\n(C)(1), Discard a Card: Recover this Card.",
    ccc: 2,
    artist: 'Robert Nix',
    rarity: Rarity.Epic,
  },
  {
    name: 'Ruffian',
    filename: 'ruffian',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(C): When this Card attacks as the first action of the turn, it gains +1Pwr until end of turn.',
    ccc: 4,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Common,
  },
  {
    name: 'Sabotage',
    filename: 'sabotage',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Dark],
    hp: 0,
    power: 3,
    speed: 0,
    text: "Destroy target (C) non-Shrine Structure if its Pwr is less than this Card's Pwr.\nDarkbound: Draw a Card. (This Card gains the added text if its Essence is Dark.)",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Scourge Opportunist',
    filename: 'scourgeopportunist',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Neutral, Element.Dark, Element.Dark],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(C): When this Card attacks as the first action of the turn, it gains Stealth 1 until end of turn.',
    ccc: 1,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Scourge Shooter',
    filename: 'scourgeshooter',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Assassin',
    cost: [Element.Neutral, Element.Air, Element.Dark],
    hp: 1,
    power: 1,
    speed: 2,
    text: '(C): Accuracy.\n(C): Lethal.\n(C): Stealth 1.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Secret Keeper',
    filename: 'secretkeeper',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Dark],
    hp: 3,
    power: 1,
    speed: 1,
    text: '(C): +2 Initiative.\n(C): (↷): If activated as the first action of the turn, take two additional actions that count as the first action of the turn.',
    ccc: 4,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Common,
  },
  {
    name: 'Secrets in the Dark',
    filename: 'secretsinthedark',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, take two additional actions that count as the first action of the turn. You may only play one "Secrets in the Dark" per turn.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Siege Master',
    filename: 'siegemaster',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Fire, Element.Fire, Element.Fire],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(C): Increase non-combat damage dealt to (C) Enemy Structures by 1.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Siege Trebuchet',
    filename: 'siegetrebuchet',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Fire, Element.Fire],
    hp: 3,
    power: 1,
    speed: 1,
    text: "(C): At end of turn, deal damage equal to this Card's Pwr to target (C) Shrine.",
    ccc: 2,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Common,
  },
  {
    name: 'Sky Devotee',
    filename: 'skydevotee',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Air, Element.Air],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(C): Airbound: Steadfast.\n(C): When you play an Air Event, this Card gains +1Spd and +1Pwr until end of turn.',
    ccc: 3,
    artist: 'Glen Fernandez',
    rarity: Rarity.Common,
  },
  {
    name: 'Sky Totem',
    filename: 'skytotem',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Air, Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(C): When you play an Air Event, you may have target (C) Air Unit gain +1Spd and +1Pwr until end of turn.',
    ccc: 2,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Slayer Squad Recruit',
    filename: 'slayersquadrecruit',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Fire, Element.Fire],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(C): While attacking, this Card gains Armor 1. (Armor decreases any damage received by 1.)\n(C): Evasion 1. (Opponents must pay an additional (1) to target this Card.)',
    ccc: 4,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Common,
  },
  {
    name: 'Standard Issue Falchion',
    filename: 'standardissuefalchion',
    epic: false,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Fire, Element.Fire],
    hp: 1,
    power: 2,
    speed: 0,
    text: "Links to a (C) non-Epic Unit.\n(C): When this Card enters play, recover Linked Unit.\n(C): Linked Unit gains the Subtype Soldier.\n(C): Linked Unit gains this Card's Pwr.",
    ccc: 6,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
  },
  {
    name: "Stranger's Fanatic",
    filename: 'strangersfanatic',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Neutral, Element.Light, Element.Light, Element.Light],
    hp: 3,
    power: 1,
    speed: 1,
    text: '(C): For each (C) Cleric you control, this Card gains +1Spd and +1Pwr.\n(C): Destroy this Card: Negate target (S) Unit.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
  },
  {
    name: 'Strongarm Thug',
    filename: 'strongarmthug',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human',
    cost: [Element.Neutral, Element.Dark],
    hp: 1,
    power: 2,
    speed: 2,
    text: '(C): When this Card deals combat damage to an Enemy Shrine, draw a Card.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Sudden Strength',
    filename: 'suddenstrength',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Earth, Element.Earth],
    hp: 0,
    power: 0,
    speed: 1,
    text: "Target (C) Unit gains this Card's Spd and Pwr until end of turn. That Unit cannot be destroyed until end of turn.",
    ccc: 1,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Take Root',
    filename: 'takeroot',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Links to a (C) Unit.\n(C): Linked Unit cannot attack.\n(C): Linked Unit's active abilities cannot be used.",
    ccc: 3,
    artist: 'Guillermo Villarreal',
    rarity: Rarity.Common,
  },
  {
    name: 'Talia - The Waveshaper',
    filename: 'taliathewaveshaper',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human Craftsman',
    cost: [Element.Water, Element.Water, Element.Water],
    hp: 4,
    power: 4,
    speed: 3,
    text: '(C): When this Card enters play, return target (R) Card you own to your hand. Draw a Card. Place a Card from your hand into your resource zone exhausted.',
    ccc: 0,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Epic,
  },
  {
    name: 'Targeted Strike',
    filename: 'targetedstrike',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 1,
    text: 'Target (C) Unit you control deals damage equal to its Pwr to target (C) Enemy Unit.',
    ccc: 6,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Temple Dedicant',
    filename: 'templededicant',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Neutral, Element.Neutral, Element.Air],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): Swiftstrike 3. (Swiftstrike increases damage by 3 while in combat with a Unie with less Spd.)',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
  },
  {
    name: "Thaddeus's Neophyte",
    filename: 'thaddeussneophyte',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Neutral, Element.Light, Element.Light],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(C): When this Card enters play, heal 3 damage from target (C) Card.',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
  },
  {
    name: 'Thaddeus - Stranger',
    filename: 'thaddeusstranger',
    epic: true,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Neutral, Element.Neutral, Element.Light, Element.Light],
    hp: 5,
    power: 2,
    speed: 1,
    text: '(C): (A)(L): Heal all damage from another target (C) non-Shrine card you control.\n(C): (A)(L): Recover this Card.',
    ccc: 2,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
  },
  {
    name: 'The Abyss',
    filename: 'theabyss',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Assassin',
    cost: [Element.Neutral, Element.Dark, Element.Dark, Element.Dark],
    hp: 6,
    power: 3,
    speed: 2,
    text: "(C): Lethal. (A Lethal Card's combat damage immediately destroys Units.)\n(C): (D)(D)(D)(D): This Card gains +1Spd until end of turn.",
    ccc: 1,
    artist: 'P.J. C. Grande',
    rarity: Rarity.Common,
  },
  {
    name: 'Through the Keyhole',
    filename: 'throughthekeyhole',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Air, Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Exhaust target (C) Unit.\nTarget (C) Unit gains Stealth 1 until end of turn.',
    ccc: 2,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Totem Keeper',
    filename: 'totemkeeper',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Neutral, Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(C): When you play an Air Event, this Card gains +1Spd and +1Pwr until end of turn.',
    ccc: 4,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Towerwright',
    filename: 'towerwright',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Tactician',
    cost: [Element.Neutral, Element.Light, Element.Light],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(C): All (C) non-Shrine Structures you control gain +1Spd and +1Pwr.',
    ccc: 3,
    artist: 'Glen Fernandez',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Triage',
    filename: 'triage',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Light],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Heal damage equal to this Card's HP from target (C) Unit.\n(S): For each (C) Cleric you control, this Card gains +1HP.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'True Believer',
    filename: 'truebeliever',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Cleric Warrior',
    cost: [Element.Neutral, Element.Light, Element.Light, Element.Light],
    hp: 5,
    power: 1,
    speed: 2,
    text: '(C): Regenerate 4.\n(C): Sworn Enemy (F), (W), (D): +3Pwr.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
  },
  {
    name: 'Underwater Spearman',
    filename: 'underwaterspearman',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Soldier',
    cost: [Element.Neutral, Element.Water],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(C): Waterbound: +1HP. (This Card gains the added text if its Essence is Water.)',
    ccc: 3,
    artist: 'Untung Forevers',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Unseen Tactics',
    filename: 'unseentactics',
    epic: false,
    supertype: CardType.ContinuousEvent,
    subtype: '',
    cost: [Element.Neutral, Element.Water, Element.Water],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(C): All (C) Units you control gain Pwr equal to their Stealth value.',
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'War Kitten',
    filename: 'wakittentoken',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Cat - Fire',
    cost: [],
    hp: 1,
    power: 1,
    speed: 2,
    text: '',
    ccc: 0,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: "War Cat's Mane - Gift of Rage",
    filename: 'warcatsmanegiftofrage',
    epic: true,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Neutral, Element.Fire, Element.Fire],
    hp: 1,
    power: 4,
    speed: 1,
    text: "Links to a (C) Unit you control.\n(C): When this Card enters play, exhaust all (C) Units if their Pwr is less than this Card's Pwr.\n(C): Linked Unit gains Armor equal to this Card's HP and Swiftstrike equal to this Card's Spd.",
    ccc: 2,
    artist: 'Untung Forevers',
    rarity: Rarity.Epic,
  },
  {
    name: 'Wardsmith',
    filename: 'wardsmith',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Craftsman',
    cost: [Element.Water],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(C): Evasion 4.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
  },
  {
    name: 'Wash Away',
    filename: 'washaway',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Water],
    hp: 0,
    power: 0,
    speed: 3,
    text: 'Destroy target (C) Item.',
    ccc: 3,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
  },
  {
    name: 'Watch Tower',
    filename: 'watchtower',
    epic: false,
    supertype: CardType.Structure,
    subtype: '',
    cost: [Element.Neutral, Element.Light],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(C): All (C) Units lose Stealth.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Wave Mender',
    filename: 'wavemender',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Cleric',
    cost: [Element.Neutral, Element.Light, Element.Water],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(C): When this Card enters play, heal 1 damage from all (C) Cards you control.',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
  },
  {
    name: 'Whispers in the Wind',
    filename: 'whispersinthewind',
    epic: false,
    supertype: CardType.Event,
    subtype: '',
    cost: [Element.Neutral, Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Draw two Cards then discard a Card.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
  },
  {
    name: 'Wind Howler',
    filename: 'windhowler',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Shaman',
    cost: [Element.Neutral, Element.Air, Element.Air],
    hp: 3,
    power: 2,
    speed: 3,
    text: '(C): When this Card enters play, draw a Card.\n(C): When this Card enters play, discard any number of Cards. Deal damage equal to the number of Cards discarded this way to all other (C) Units.',
    ccc: 1,
    artist: 'Adriano Oliveira & Fernando Cordeiro',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Wind Whisperer',
    filename: 'windwhisperer',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Shaman',
    cost: [Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(C): When this Card enters play, draw a Card.',
    ccc: 4,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
  },
  {
    name: 'Wolf-Heart Shaman',
    filename: 'wolf-heartshaman',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Shaman',
    cost: [Element.Neutral, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: "(C): When this Card enters play, return target (C) Enemy Unit to its owner's hand if its Spd is less than this Card's Spd.",
    ccc: 1,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
  },
  {
    name: "X - True King's Sword",
    filename: 'xtruekingssword',
    epic: true,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Neutral, Element.Earth, Element.Earth],
    hp: 5,
    power: 2,
    speed: 0,
    text: "Links to a (C) Unit you control.\n(C): If Linked Unit is Earth, it gains the Subtype King and this Card gains +1Spd.\n(C): Linked Unit gains this Card's Pwr.\n(C): Destroy this Card: Negate Target (S) Event.\n(D): Use this ability only if you control a (C) King; (E)(E): Return this Card to your hand.",
    ccc: 4,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Epic,
  },
  {
    name: 'Yawatarara Disciple',
    filename: 'yawataradisciple',
    epic: false,
    supertype: CardType.Unit,
    subtype: 'Human Warrior',
    cost: [Element.Neutral, Element.Water, Element.Water, Element.Water],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(C): When this Card enters play, return target (D) Water Event you own to your hand.\n(C): When you play a Water Event, this Card gains Stealth 1 until end of turn.',
    ccc: 2,
    artist: 'Untung Forevers',
    rarity: Rarity.Uncommon,
  },
  {
    name: 'Zi Tapestry - Esoteric Lore',
    filename: 'zitapestryesotericlore',
    epic: true,
    supertype: CardType.Item,
    subtype: '',
    cost: [Element.Neutral, Element.Dark],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (C) Dark Structure you control.\n(C): For each damage on Linked Structure, this Card gains +1 Initiative.\n(C): (1), Exhaust Linked Structure: Your next action this turn counts as the first action of the turn.',
    ccc: 6,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Epic,
  },
];
