import { CardType } from '../components/card';
import { BaseCardType, Element, Rarity } from './enums';
import { Essence, essences } from './essences';
export class BaseCardFilters {
  private type: (supertype: BaseCardType) => boolean;
  private identity: (pips: Element[]) => boolean;
  private cost: (cost: number) => boolean;
  private query: (fields: string[]) => boolean;
  private rarity: (rarity: Rarity) => boolean;
  ccc: (ccc: number) => boolean;
  // speed: (speed: number) => boolean;

  constructor({
    typeChoice,
    elementChoices,
    elementOperator,
    costChoiceOne,
    costChoiceTwo,
    costOperator,
    cccChoice,
    cccOperator,
    query,
    rarityFilter,
  }: {
    typeChoice: BaseCardType;
    elementChoices: Element[];
    elementOperator: boolean | undefined;
    costChoiceOne: number;
    costChoiceTwo: number;
    costOperator: string;
    cccChoice: number;
    cccOperator: string;
    query: string;
    rarityFilter: Rarity;
  }) {
    this.type =
      typeChoice === BaseCardType.Any
        ? (supertype: BaseCardType) => true
        : (supertype: BaseCardType) => {
            return typeChoice === supertype;
          };
    if (elementChoices.length > 0) {
      switch (elementOperator) {
        case undefined: // or
          this.identity = (pips: Element[]) => {
            return elementChoices.some((el) => pips.includes(el));
          };
          break;
        case false: // and
          this.identity = (pips: Element[]) => {
            return elementChoices.every((el) => pips.includes(el));
          };
          break;
        case true: // only
          this.identity = (pips: Element[]) => {
            return pips.every((el) => elementChoices.includes(el));
          };
      }
    } else {
      this.identity = (pips: Element[]) => true;
    }
    if (costChoiceOne) {
      switch (costOperator) {
        case '=':
          this.cost = (cost: number) => costChoiceOne === cost;
          break;
        case '<=':
          this.cost = (cost: number) => cost <= costChoiceOne;
          break;
        case '>=':
          this.cost = (cost: number) => cost >= costChoiceOne;
          break;
        case '<=>':
          if (costChoiceTwo) {
            this.cost = (cost: number) => {
              const diff = Math.abs(costChoiceOne - costChoiceTwo);
              return (
                diff >= Math.abs(costChoiceOne - cost) &&
                diff >= Math.abs(costChoiceTwo - cost)
              );
            };
          } else {
            // can't apply 'between' filter until there are two numbers, default to 'equals' filter
            this.cost = (cost: number) => cost === costChoiceOne;
          }
          break;
        default:
          console.warn('Invalid cost filter operator');
      }
    } else {
      this.cost = (cost: number) => true;
    }
    if (Number.isNaN(cccChoice)) {
      this.ccc = (ccc: number) => true;
    } else {
      switch (cccOperator) {
        case '<=':
          this.ccc = (ccc: number) => ccc <= cccChoice;
          break;
        case '=':
          this.ccc = (ccc: number) => ccc === cccChoice;
          break;
        case '>=':
          this.ccc = (ccc: number) => ccc >= cccChoice;
          break;
        default:
          console.warn('Invalid cost filter operator');
      }
    }
    this.query = query
      ? (fields: string[]) =>
          fields.some((s) => {
            return s.toLocaleLowerCase().includes(query.toLocaleLowerCase());
          })
      : (fields: string[]) => true;
    this.rarity =
      rarityFilter === Rarity.Any
        ? (rarity: Rarity) => true
        : (rarity: Rarity) => rarity === rarityFilter;
  }

  keep(c: BaseCard): boolean {
    return (
      this.type(c.supertype) &&
      this.identity(c.pips) &&
      this.cost(c.cost) &&
      this.ccc(c.ccc) &&
      this.query([c.name, c.subtype, c.text, c.artist]) &&
      this.rarity(c.rarity)
    );
  }
}

class UncalculatedBaseCard {
  name: string;
  filename: string;
  id: number;
  epic: boolean;
  supertype: BaseCardType;
  subtype: string;
  cost: number;
  pips: Element[];
  hp: number;
  power: number;
  speed: number;
  text: string;
  ccc: number;
  artist: string;
  rarity: Rarity;
  type: CardType;
  isValidEssence: (e: Essence) => boolean;
}

export class BaseCard {
  name: string;
  filename: string;
  id: number;
  epic: boolean;
  supertype: BaseCardType;
  subtype: string;
  cost: number;
  pips: Element[];
  hp: number;
  power: number;
  speed: number;
  text: string;
  ccc: number;
  artist: string;
  rarity: Rarity;
  type: CardType;
  isValidEssence: (e: Essence) => boolean;
  validEssences: Set<number>;
}

const uncalculatedBaseCards: UncalculatedBaseCard[] = [
  {
    name: 'Absorb Magic',
    filename: 'absorbmagic',
    id: 0,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Earth, Element.Earth],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Negate target (Stack) Event.',
    ccc: 2,
    artist: 'J.C. Grande',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Aegis Greenhorn',
    filename: 'aegisgreenhorn',
    id: 1,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 1,
    pips: [Element.Earth],
    hp: 3,
    power: 2,
    speed: 1,
    text: '(Combat): While defending, this Card gains Armor 1. (Armor decreases any damage received by 1.)',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Alleyway Intimidator',
    filename: 'alleywayintimidator',
    id: 2,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Mercenary',
    cost: 3,
    pips: [Element.Dark],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(Combat): While attacking a (Combat) Shrine you control, Units have their Stealth value decreased by 1.\n (Combat): Any player may use this ability; (5): Destroy target (Combat) Unit if it has Stealth.',
    ccc: 3,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Armentia - Celestial Spear',
    filename: 'armentiacelestialspear',
    id: 3,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Light, Element.Light],
    hp: 3,
    power: 0,
    speed: 5,
    text: 'Links to a (Combat) Unit.\n (Combat): Linked Unit gains +1 Spd.\n (Combat): Linked Unit gains "When this Card deals combat damage to a Unit, Daze that Unit."\n (Combat): If Linked Unit is Light, it gains Accuracy.',
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Light) >= 0;
    },
  },
  {
    name: 'Arsonist',
    filename: 'arsonist',
    id: 4,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 4,
    pips: [Element.Dark, Element.Fire],
    hp: 4,
    power: 2,
    speed: 2,
    text: "(Combat): Darkbound: +1 Pwr.\n (Combat): Firebound: +2 Initiative.\n (Combat): When this Card enters play, if it was played as the first action of the turn, deal damage equal to this Card's Pwr to target (Combat) Structure.",
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Avarisa Darkhart - Silver Tongued',
    filename: 'avarisadarkhartsilvertongued',
    id: 5,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 2,
    pips: [Element.Dark, Element.Dark],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): Your first action each turn counts as the first action of the turn.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Backstab',
    filename: 'backstab',
    id: 6,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Dark, Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, destroy target (Combat) Unit. If you control a (Combat) Assassin, draw a Card.',
    ccc: 6,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Banishment',
    filename: 'banishment',
    id: 7,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Light],
    hp: 4,
    power: 0,
    speed: 2,
    text: "Negate target (Stack) Unit if its Pwr is less than this Card's HP.\n (Stack): While you control a (Combat) Cleric, this Card gains +1 HP.",
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Barracks',
    filename: 'barracks',
    id: 8,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Fire],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): All (Combat) Fire Units you control gain +1 Pwr.\n (Combat): (Exhaust): Target (Combat) Soldier gains +1 Spd until end of turn.',
    ccc: 6,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Battlefield Headsman',
    filename: 'battlefieldheadsman',
    id: 9,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): When a (Combat) Enemy Unit is destroyed for the first time each turn, recover this Card.',
    ccc: 1,
    artist: 'Ray of Sand',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Best Laid Plans',
    filename: 'bestlaidplans',
    id: 10,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Light],
    hp: 3,
    power: 0,
    speed: 0,
    text: "Take a number of additional actions equal to this Card's HP. After these actions, all your future actions this turn must be pass.",
    ccc: 1,
    artist: 'Megan Toole',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Binding Chains',
    filename: 'bindingchains',
    id: 11,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 2,
    power: 1,
    speed: 0,
    text: "Links to an exhausted (Combat) Unit.\n (Combat): Linked Unit does not recover at the start of each turn.\n (Combat): At end of turn, deal damage equal to this Card's Pwr to Linked Unit.",
    ccc: 2,
    artist: 'Guillermo Villarreal',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Bladeborne Dreng',
    filename: 'bladebornedreng',
    id: 12,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 2,
    pips: [Element.Fire, Element.Air],
    hp: 1,
    power: 3,
    speed: 2,
    text: '(Combat): When this Card enters play, deal 1 damage to target (Combat) Unit or (Combat) Structure.',
    ccc: 3,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Air) >= 0;
    },
  },
  {
    name: 'Blue Back Strategist',
    filename: 'bluebackstrategist',
    id: 13,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 3,
    pips: [Element.Water, Element.Water],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): Stealth 1.\n (Combat): Waterbound: All (Combat) Units you control with Stealth cannot be attacked.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Brute',
    filename: 'brute',
    id: 14,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Barbarian',
    cost: 2,
    pips: [Element.Air],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(Combat): At end of turn, discard a Card.',
    ccc: 4,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Burst of Speed',
    filename: 'burstofspeed',
    id: 15,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Target (Combat) Unit gains this Card's Spd and Swiftstrike 2 until end of action.",
    ccc: 2,
    artist: 'Rafael Lenhellas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Bury Magic',
    filename: 'burymagic',
    id: 16,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Place target (Combat) Continuous Event or (Combat) Item into its controller's resource zone exhausted.",
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Call Lightning',
    filename: 'calllightning',
    id: 17,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Air],
    hp: 0,
    power: 2,
    speed: 1,
    text: "Deal damage equal to this Card's Pwr to target (Combat) Unit.\n (Stack): Airbound: +1 Pwr. (This Card gains the added text if its Essence is Air.)",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Call Wind',
    filename: 'callwind',
    id: 18,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Exhaust target (Combat) Unit.\n Airbound: Exhaust target (Combat) Unit. You may discard a Card, if you do, exhaust target (Combat) Unit.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Careful Sneak',
    filename: 'carefulsneak',
    id: 19,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 1,
    pips: [Element.Water],
    hp: 2,
    power: 2,
    speed: 1,
    text: '(Combat): Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Churn',
    filename: 'churn',
    id: 20,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Return target (Resource) Card you own to your hand. Draw a Card. Place a Card from your hand into your resource zone exhausted.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Cleanse',
    filename: 'cleanse',
    id: 21,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Light],
    hp: 0,
    power: 0,
    speed: 3,
    text: 'Destroy target (Combat) Continuous Event.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Combat Medic',
    filename: 'combatmedic',
    id: 22,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 1,
    pips: [Element.Light],
    hp: 2,
    power: 0,
    speed: 0,
    text: "(Combat): (Exhaust): (3): Heal damage equal to this Card's HP from another target (Combat) Unit.",
    ccc: 1,
    artist: 'Lee Sands',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Conjure Barrier',
    filename: 'conjurebarrier',
    id: 23,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 4,
    text: 'Target (Combat) Shrine cannot take damage until end of turn. All your future actions this turn must be pass.',
    ccc: 2,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Counter Assassin',
    filename: 'counterassassin',
    id: 24,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Assassin',
    cost: 3,
    pips: [Element.Dark, Element.Dark],
    hp: 2,
    power: 3,
    speed: 2,
    text: '(Combat): When this Card enters play, you may destroy target (Combat) Unit if it has Stealth.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Covert Operation',
    filename: 'covertoperation',
    id: 25,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Target (Combat) Unit gains Stealth 2 until end of turn. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)\n Darkbound: Draw a Card. (This Card gains the added text if its Essence is Dark)',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Cutthroat',
    filename: 'cutthroat',
    id: 26,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Assassin',
    cost: 4,
    pips: [Element.Dark, Element.Dark],
    hp: 3,
    power: 2,
    speed: 2,
    text: "(Combat): Stealth 1.\n (Combat): Darkbound: +1 Spd and +1 Pwr.\n (Combat): When this Card enters play, you may destroy target (Combat) Unit if its Spd is less than this Card's Pwr.",
    ccc: 2,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Demolition Vanguard',
    filename: 'demolitionvanguard',
    id: 27,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 3,
    pips: [Element.Water, Element.Water],
    hp: 2,
    power: 4,
    speed: 2,
    text: '(Combat): Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)\n (Combat): This Card may only attack Structures.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Devoted Defender',
    filename: 'devoteddefender',
    id: 28,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 4,
    pips: [Element.Light],
    hp: 6,
    power: 2,
    speed: 2,
    text: '(Combat): While defending, this Card gains +2Spd and +2Pwr.',
    ccc: 2,
    artist: 'Lee Sands',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Disbelief',
    filename: 'disbelief',
    id: 29,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Water, Element.Water, Element.Water],
    hp: 0,
    power: 0,
    speed: 2,
    text: "Move target (Combat) non-Shrine Epic Card to the bottom of its owner's deck.",
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Disgraced Veteran',
    filename: 'disgracedveteran',
    id: 30,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 2,
    pips: [Element.Dark, Element.Fire],
    hp: 2,
    power: 3,
    speed: 1,
    text: "(Combat): Lethal. (A Lethal Card's combat damage immediately destroys Units.)",
    ccc: 3,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Distrust',
    filename: 'distrust',
    id: 31,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 2,
    pips: [Element.Water, Element.Earth],
    hp: 1,
    power: 0,
    speed: 3,
    text: '(Combat): When this Card enters play, negate target (Stack) Event unless its controller pays (2).\n (Combat): When an opponent targets one of your Cards, place this Card into your resource zone exhausted.',
    ccc: 3,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "D'Marque Heirloom - Gilded Mask",
    filename: 'dmarqueheirloomgildedmask',
    id: 32,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 3,
    pips: [Element.Water, Element.Water],
    hp: 3,
    power: 0,
    speed: 5,
    text: 'Links to a (Combat) Human you control.\n (Combat): Linked Unit gains the Subtype Queen.\n (Combat): When Linked Unit would be destroyed for the first time each turn, you may destroy another (Combat) Human you control instead, if you do, heal all damage from Linked Unit.',
    ccc: 0,
    artist: 'Arte Express Studio',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Driis Palisade',
    filename: 'driispalisade',
    id: 33,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Earth],
    hp: 4,
    power: 0,
    speed: 1,
    text: 'All Shrines you control cannot be attacked.',
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Driis Sentry',
    filename: 'driissentry',
    id: 34,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Ranger',
    cost: 3,
    pips: [Element.Earth],
    hp: 3,
    power: 3,
    speed: 2,
    text: 'All Earth Structures you control gain Armor 1.',
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Drown',
    filename: 'drown',
    id: 35,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 4,
    text: "Destroy target (Combat) Unit if its Pwr is less than this Card's Spd.",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Dying Breath',
    filename: 'dyingbreath',
    id: 36,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Fire],
    hp: 0,
    power: 1,
    speed: 0,
    text: "Recover target (Combat) Unit you control. It gains this Card's Pwr until end of turn. At end of turn, destroy it.",
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Earthquake',
    filename: 'earthquake',
    id: 37,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 4,
    pips: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Deal 3 damage to all (Combat) Structures. Earthbound: Exhaust all (Combat) Units if their Pwr is less than the number of (Resource) Cards you control.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Earth's Elite",
    filename: 'earthselite',
    id: 38,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 4,
    pips: [Element.Earth, Element.Earth],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): Armor 1. (Armor decreases any damage received by 1.)',
    ccc: 1,
    artist: 'Robert Nix',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Elvyrra - Slayer Squad Commander',
    filename: 'elvyrraslayersquadcommander',
    id: 39,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 3,
    pips: [Element.Fire, Element.Fire],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): All (Combat) Fire Units you control gain +1Pwr.\n (Combat): When this Card deals combat damage to an Enemy Shrine, recover another target (Combat) Fire Unit you control.',
    ccc: 2,
    artist: 'Giraaz Studio',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Eternal Flame Soldier',
    filename: 'eternalflamesoldier',
    id: 40,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Soldier',
    cost: 4,
    pips: [Element.Fire],
    hp: 6,
    power: 3,
    speed: 2,
    text: '(Combat): Regenerate 1. (Heal 1 damage from this Card at end of turn.)',
    ccc: 4,
    artist: 'Robert Nix',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Expert Combatant',
    filename: 'expertcombatant',
    id: 41,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 3,
    pips: [Element.Earth],
    hp: 2,
    power: 5,
    speed: 2,
    text: '(Combat): Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 4,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Exploit Might',
    filename: 'exploitmight',
    id: 42,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Water, Element.Water],
    hp: 0,
    power: 4,
    speed: 0,
    text: "(Stack): For each (Combat) Unit you control with Stealth, this Card gains -1Pwr. Destroy target (Combat) non-Epic Unit if its Pwr is greater than this Card's Pwr.",
    ccc: 6,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Fablemonger',
    filename: 'fablemonger',
    id: 43,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 3,
    pips: [Element.Earth, Element.Light],
    hp: 4,
    power: 4,
    speed: 1,
    text: '(Combat): Lightbound: Regenerate 1.\n (Combat): Earthbound: When this Card is destroyed, place it into your resource zone exhausted.',
    ccc: 2,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Fierce Protector',
    filename: 'fierceprotector',
    id: 44,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 6,
    pips: [Element.Earth, Element.Earth, Element.Earth],
    hp: 5,
    power: 5,
    speed: 2,
    text: '(Combat): Steadfast.\n (Combat): When you play an Earth Card, heal 1 damage from target (Combat) Shrine.\n (Combat): When you Surge, increase the Surge value by 1.',
    ccc: 2,
    artist: 'J. C. Grande',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Fighter's Heart",
    filename: 'fightersheart',
    id: 45,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 2,
    pips: [Element.Air],
    hp: 1,
    power: 1,
    speed: 0,
    text: "Links to a (Combat) Unit.\n (Combat): Linked Unit gains this Card's Pwr.\n (Combat): If Linked Unit is Air, it gains Steadfast.",
    ccc: 1,
    artist: 'Kayla Raney',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Finishing Move',
    filename: 'finishingmove',
    id: 46,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 4,
    pips: [Element.Fire, Element.Fire],
    hp: 0,
    power: 2,
    speed: 4,
    text: "Negate target (Stack) Card. If that Card has cost 3 or less, deal damage equal to this Card's Pwr to target Shrine controlled by the same player as the negated Card.",
    ccc: 2,
    artist: 'Robert Nix',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Firebomb',
    filename: 'firebomb',
    id: 47,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Deal 1 damage to all Units (Combat) and (Combat) all Structures.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Fire Palm Strike',
    filename: 'firepalmstrike',
    id: 48,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Fire],
    hp: 0,
    power: 2,
    speed: 1,
    text: "Target (Combat) Unit gains this Card's Pwr until end of turn.",
    ccc: 3,
    artist: 'Vicar Tochi',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'First Strike',
    filename: 'firststrike',
    id: 49,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, destroy target (Combat) Unit if it has cost 2 or less. Otherwise, destroy target (Combat) Unit if it has cost 1 or less.',
    ccc: 3,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Fountain of Life',
    filename: 'fountainoflife',
    id: 50,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Light, Element.Water],
    hp: 8,
    power: 0,
    speed: 0,
    text: '(Combat): (Exhaust), Exhaust a (Combat) Unit: Move any amount of damage from that Unit to this Card.',
    ccc: 2,
    artist: 'Kateryna Vitkovska',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Funeral Pyre',
    filename: 'funeralpyre',
    id: 51,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 1,
    pips: [Element.Fire],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(Combat): All (Dead) Cards lose all abilities.\n (Combat): All (Dead) Cards cannot be targeted.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Gale Warrior',
    filename: 'galewarrior',
    id: 52,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 3,
    pips: [Element.Fire, Element.Air],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): Airbound: +1Spd and +1Pwr. (Combat): Firebound: +1Spd and +1Pwr.',
    ccc: 3,
    artist: 'Robert Nix',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Garrison',
    filename: 'garrison',
    id: 53,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 1,
    pips: [Element.Light],
    hp: 1,
    power: 0,
    speed: 5,
    text: 'Links to a (Combat) Structure.\n (Combat): Linked Structure may defend as if it were a Unit.',
    ccc: 6,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Griffin IV - Earth Splitter',
    filename: 'griffinivearthsplitter',
    id: 54,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human King',
    cost: 6,
    pips: [Element.Earth, Element.Earth],
    hp: 7,
    power: 0,
    speed: 2,
    text: '(Stack)(Combat): This Card gains Pwr equal to the number of (Resource) Cards you control.\n (Combat): Earthbound: When this Card is destroyed, place it into your resource zone exhausted.',
    ccc: 6,
    artist: 'Kayla Raney',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Grizzled Crop Keeper',
    filename: 'grizzledcropkeeper',
    id: 55,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Earth],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(Combat): (Exhaust): Surge 2. (Recover up to 2 (Resource) Cards you control.)\n (Resource): (Exhaust): (Resource)',
    ccc: 6,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Grunt',
    filename: 'grunt',
    id: 56,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 1,
    pips: [Element.Fire],
    hp: 2,
    power: 2,
    speed: 2,
    text: '',
    ccc: 3,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Guardian of The Sacred Grove',
    filename: 'guardianofthesacredgrove',
    id: 57,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Earth],
    hp: 6,
    power: 1,
    speed: 1,
    text: '(Combat): Steadfast. (Defends without exhausting.)',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Guard Shack',
    filename: 'guardshack',
    id: 58,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Light],
    hp: 4,
    power: 1,
    speed: 1,
    text: '(Combat): This Card may defend as if it were a Unit.',
    ccc: 2,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Gust',
    filename: 'gust',
    id: 59,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Return target (Combat) non-Shrine Card to its owner's hand.\n (Stack): Accuracy. (Events with Accuracy ignore Evasion.)",
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Hatred',
    filename: 'hatred',
    id: 60,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Dark, Element.Fire],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Destroy target (Combat) Unit if it is Light, Water or Earth.',
    ccc: 2,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Heat Stroke',
    filename: 'heatstroke',
    id: 61,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 2,
    pips: [Element.Fire, Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Links to a (Combat) Unit.\n At end of turn, Linked Unit's controller discards a Card or destroys Linked Unit.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Highland Isolationist',
    filename: 'highlandisolationist',
    id: 62,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 3,
    pips: [Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): While you control no other (Combat) Units, this Card gains +1Spd, +2Pwr and +3HP.',
    ccc: 4,
    artist: 'Untung Forevers',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Holy Symbol',
    filename: 'holysymbol',
    id: 63,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Light, Element.Water],
    hp: 1,
    power: 0,
    speed: 5,
    text: "Links to a (Combat) Unit.\n (Combat): Linked Unit cannot be targeted by Fire, Air or Dark Cards.\n (Combat): If Linked Unit is a Cleric, it gains this Card's HP.",
    ccc: 3,
    artist: 'Francisco K. Pérez Ortiz',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Hurricane',
    filename: 'hurricane',
    id: 64,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Air, Element.Air],
    hp: 0,
    power: 1,
    speed: 0,
    text: "Deal damage equal to this Card's Pwr to all (Combat) Units.\n (Stack): Airbound: +1Pwr.",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Icy Skin',
    filename: 'icyskin',
    id: 65,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 3,
    pips: [Element.Water],
    hp: 5,
    power: 0,
    speed: 1,
    text: "Links to a (Combat) Human.\n (Combat): Linked Unit gains 'This Card only takes combat damage from (Combat) Fire Units.'",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Intelligence Operative',
    filename: 'intelligenceoperative',
    id: 66,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 2,
    pips: [Element.Dark],
    hp: 4,
    power: 1,
    speed: 1,
    text: '(Combat): Stealth 1. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)\n (Combat): +2 Initiative.',
    ccc: 3,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Invisible Force',
    filename: 'invisibleforce',
    id: 67,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Air, Element.Dark],
    hp: 0,
    power: 4,
    speed: 0,
    text: "Return target (Combat) Enemy Unit to its owner's hand. If that Unit has less Pwr than this Card, draw a Card.",
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Knife Expert',
    filename: 'knifeexpert',
    id: 68,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Assassin Tactician',
    cost: 2,
    pips: [Element.Dark, Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): Stealth 1.\n (Combat): When this Card attacks as the first action of the turn, take an additional action that counts as the first action of the turn.',
    ccc: 2,
    artist: 'Kayla Raney',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Life Cycle Warden',
    filename: 'lifecyclewarden',
    id: 69,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 4,
    pips: [Element.Water, Element.Earth],
    hp: 5,
    power: 4,
    speed: 2,
    text: '(Combat): When this Card enters play, return target (Resource) Card you own to your hand.',
    ccc: 4,
    artist: 'Robert Nix',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Light Lance',
    filename: 'lightlance',
    id: 70,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 3,
    pips: [Element.Earth, Element.Earth],
    hp: 1,
    power: 0,
    speed: 5,
    text: 'Links to a (Combat) Unit.\n (Combat): Linked Unit gains Accuracy. (Attackers with Accuracy may attack recovered Units.)\n (Combat): If Linked Unit is a Knight, it gains +1Spd.',
    ccc: 6,
    artist: 'J. C. Grande',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Lightning Warrior',
    filename: 'lightningwarrior',
    id: 71,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 5,
    pips: [Element.Air, Element.Air],
    hp: 4,
    power: 3,
    speed: 2,
    text: "(Combat): When this Card enters play, you may Daze target (Combat) Unit.\n (Combat): (1)(A), (Exhaust): Move target (Dead) 'Call Lightning' you own to the bottom of your deck, if you do, deal damage equal to this Card's Pwr to target (Combat) Unit.",
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Little Breeze - A New Way',
    filename: 'littlebreezeanewway',
    id: 72,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Shaman',
    cost: 4,
    pips: [Element.Air, Element.Air],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, draw a Card.\n (Combat): Airbound: When this Card enters play, draw a Card.\n (Combat): (1), Discard a Card: Exhaust target (Combat) Unit.',
    ccc: 2,
    artist: 'Chris Jones',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Lowland Hunter',
    filename: 'lowlandhunter',
    id: 73,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Ranger Soldier',
    cost: 2,
    pips: [Element.Earth, Element.Light],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): Accuracy. (Attackers with Accuracy may attack recovered Units.)\n (Combat): Sworn Enemy (Air): +4Spd. (This Card gains the added text while in combat with a Unit of the listed variety.)',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Melee Alumnus',
    filename: 'meleealumnus',
    id: 74,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 4,
    pips: [Element.Fire],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(Combat): Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 1,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Mend',
    filename: 'mend',
    id: 75,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Light, Element.Light],
    hp: 5,
    power: 0,
    speed: 0,
    text: "Heal damage equal to this Card's HP from target (Combat) Card.",
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Might of the Earth',
    filename: 'mightoftheearth',
    id: 76,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 3,
    pips: [Element.Earth, Element.Earth, Element.Earth],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Earth Unit.\n (Combat): Linked Unit gains Pwr equal to the number of (Resource) Earth Cards you control.',
    ccc: 6,
    artist: 'Lee Sands',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Mikiri Frontliner',
    filename: 'mikirifrontliner',
    id: 77,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 3,
    pips: [Element.Fire, Element.Fire],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): Accuracy. (Attackers with Accuracy may attack recovered Units.)',
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Natural Forces',
    filename: 'naturalforces',
    id: 78,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Water, Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Place target (Combat) Unit into its controller's resource zone exhausted, if you do, that player returns another (Resource) Card they own to their hand.",
    ccc: 2,
    artist: 'Kayla Raney',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Nature's Divinity",
    filename: 'naturesdivinity',
    id: 79,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 3,
    pips: [Element.Earth, Element.Light],
    hp: 2,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Unit or (Combat) Structure.\n (Combat): If Linked Card is Light, it gains Regenerate 2.\n (Combat): If Linked Card is Earth, it gains Armor 1.',
    ccc: 2,
    artist: 'Megan Toole',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Night Watch',
    filename: 'nightwatch',
    id: 80,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Light],
    hp: 4,
    power: 2,
    speed: 1,
    text: '(Combat): While you control a (Combat) Structure that may defend as if it were a Unit, this Card gains +1Spd and +1Pwr.',
    ccc: 4,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Novice Sellsword',
    filename: 'novicesellsword',
    id: 81,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Mercenary',
    cost: 2,
    pips: [Element.Dark],
    hp: 4,
    power: 3,
    speed: 3,
    text: '(Combat): -5 Initiative.',
    ccc: 6,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Nullifier',
    filename: 'nullifier',
    id: 82,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Knight',
    cost: 4,
    pips: [Element.Earth, Element.Earth, Element.Earth],
    hp: 4,
    power: 4,
    speed: 1,
    text: '(Combat): Earthbound: At end of turn, each opponent destroys a (Combat) Continuous Event they control.',
    ccc: 2,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Old Man Gerhalt - Trinity Speaker',
    filename: 'oldmangerhalttrinityspeaker',
    id: 83,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 6,
    pips: [Element.Light, Element.Water, Element.Earth],
    hp: 3,
    power: 3,
    speed: 3,
    text: "(Combat): When this Card enters play, heal damage equal to this Card's HP from target (Combat) Shrine.\n (Combat): Lightbound: +3HP.\n (Combat): Waterbound: +3Pwr.\n (Combat): Earthbound: When this Card is destroyed, place it into your resource zone exhausted.",
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Partisan',
    filename: 'partisan',
    id: 84,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 4,
    pips: [Element.Water],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(Combat): Stealth 2. (A Stealth attack can only be defended by a defender with equal or greater Stealth value.)',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Payday',
    filename: 'payday',
    id: 85,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If you control a (Combat) Assassin, draw a Card. If you control a (Combat) Tactician, draw a Card. If all (Combat) Enemy Structures are damaged, draw a Card.',
    ccc: 4,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Pillory',
    filename: 'pillory',
    id: 86,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 1,
    pips: [Element.Dark],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(Combat): (Exhaust): Target (Combat) Unit cannot attack this turn.',
    ccc: 3,
    artist: 'Megan Toole',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Pincer Maneuver',
    filename: 'pincermaneuver',
    id: 87,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'All (Combat) Units you control with Stealth gain Evasion 1 until end of turn.\n (Dead): When a Unit you control with Stealth deals combat damage to an Enemy Shrine for the first time each turn, you may deal 1 damage to target (Combat) Unit.',
    ccc: 4,
    artist: 'Omari Perez',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Planting',
    filename: 'planting',
    id: 88,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Earth],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Place the top Card of your deck into your resource zone exhausted.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Prayers Answered',
    filename: 'prayersanswered',
    id: 89,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Light, Element.Light],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Move any amount of damage from (Combat) Units you control to (Combat) Structures you control.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Quarterstaff',
    filename: 'quarterstaff',
    id: 90,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Air],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Unit you control.\n (Combat): If Linked Unit is Air, it gains +1Spd.\n (Combat): (Air)(Air), Exhaust Linked Unit: Daze target (Combat) Unit. (A Dazed Unit has its Spd set to 0 until end of turn.)',
    ccc: 6,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Quicksilver Wings - Mystic Headpiece',
    filename: 'quicksilverwingsmysticheadpiece',
    id: 91,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Unit.\n (Combat): Linked Unit gains this Card\'s Spd.\n (Combat): If Linked Unit is Air, it gains "When you discard a Card, recover this Card."\n (Combat): (1), Discard a Card: Return another target (Combat) Item or (Combat) Continuous Event to its owner\'s hand.',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Ram the Gates',
    filename: 'ramthegates',
    id: 92,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Fire],
    hp: 0,
    power: 2,
    speed: 0,
    text: "Deal damage equal to this Card's Pwr to target (Combat) Structure.",
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Re-equip',
    filename: 're-equip',
    id: 93,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Light],
    hp: 0,
    power: 0,
    speed: 0,
    text: "Return target (Dead) Item to its owner's hand.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Refugee',
    filename: 'refugee',
    id: 94,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 1,
    pips: [Element.Light],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): While you control a (Combat) non-Shrine Light Structure, this Card gains +1HP.',
    ccc: 4,
    artist: 'Francisco K. Pérez Ortiz',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Root Tender',
    filename: 'roottender',
    id: 95,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Earth],
    hp: 2,
    power: 2,
    speed: 1,
    text: '(Combat): When this Card enters play, heal 2 damage from target (Combat) Structure.\n (Combat): When this Card enters play, heal 2 damage from target (Combat) "The Great Oak."',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Royal Custodian',
    filename: 'royalcustodian',
    id: 96,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 4,
    pips: [Element.Water, Element.Water],
    hp: 4,
    power: 3,
    speed: 2,
    text: '(Combat): Evasion 2. (Opponents must pay an additional (2) to target this Card.)',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Ruebane - Fury's Avatar",
    filename: 'ruebanefurysavatar',
    id: 97,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Warrior',
    cost: 5,
    pips: [Element.Dark, Element.Fire, Element.Air],
    hp: 4,
    power: 3,
    speed: 3,
    text: "(Combat): When this Card enters play, if it was played as the first action of the turn, deal damage equal to this Card's Pwr to target (Combat) Shrine.\n (Combat): (Fire)(Fire): This Card gains Accuracy until end of turn.\n (Combat): (1), Discard a Card: Recover this Card.",
    ccc: 2,
    artist: 'Robert Nix',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Ruffian',
    filename: 'ruffian',
    id: 98,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 1,
    pips: [Element.Dark],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card attacks as the first action of the turn, it gains +1Pwr until end of turn.',
    ccc: 4,
    artist: 'Daniel Da Graca',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Sabotage',
    filename: 'sabotage',
    id: 99,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Dark],
    hp: 0,
    power: 3,
    speed: 0,
    text: "Destroy target (Combat) non-Shrine Structure if its Pwr is less than this Card's Pwr.\n Darkbound: Draw a Card. (This Card gains the added text if its Essence is Dark.)",
    ccc: 2,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Scourge Opportunist',
    filename: 'scourgeopportunist',
    id: 100,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 3,
    pips: [Element.Dark, Element.Dark],
    hp: 3,
    power: 3,
    speed: 3,
    text: '(Combat): When this Card attacks as the first action of the turn, it gains Stealth 1 until end of turn.',
    ccc: 1,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Scourge Shooter',
    filename: 'scourgeshooter',
    id: 101,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Assassin',
    cost: 3,
    pips: [Element.Air, Element.Dark],
    hp: 1,
    power: 1,
    speed: 2,
    text: '(Combat): Accuracy.\n (Combat): Lethal.\n (Combat): Stealth 1.',
    ccc: 4,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Secret Keeper',
    filename: 'secretkeeper',
    id: 102,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Dark],
    hp: 3,
    power: 1,
    speed: 1,
    text: '(Combat): +2 Initiative.\n (Combat): (Exhaust): If activated as the first action of the turn, take two additional actions that count as the first action of the turn.',
    ccc: 4,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Secrets in the Dark',
    filename: 'secretsinthedark',
    id: 103,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'If played as the first action of the turn, take two additional actions that count as the first action of the turn. You may only play one "Secrets in the Dark" per turn.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Siege Master',
    filename: 'siegemaster',
    id: 104,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 5,
    pips: [Element.Fire, Element.Fire],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): Increase non-combat damage dealt to (Combat) Enemy Structures by 1.',
    ccc: 3,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Siege Trebuchet',
    filename: 'siegetrebuchet',
    id: 105,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 4,
    pips: [Element.Fire],
    hp: 3,
    power: 1,
    speed: 1,
    text: "(Combat): At end of turn, deal damage equal to this Card's Pwr to target (Combat) Shrine.",
    ccc: 2,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Sky Devotee',
    filename: 'skydevotee',
    id: 106,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 3,
    pips: [Element.Air, Element.Air],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(Combat): Airbound: Steadfast.\n (Combat): When you play an Air Event, this Card gains +1Spd and +1Pwr until end of turn.',
    ccc: 3,
    artist: 'Glen Fernandez',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Sky Totem',
    filename: 'skytotem',
    id: 107,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 3,
    power: 0,
    speed: 0,
    text: '(Combat): When you play an Air Event, you may have target (Combat) Air Unit gain +1Spd and +1Pwr until end of turn.',
    ccc: 2,
    artist: 'Megan Toole',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Slayer Squad Recruit',
    filename: 'slayersquadrecruit',
    id: 108,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 3,
    pips: [Element.Fire, Element.Fire],
    hp: 3,
    power: 3,
    speed: 2,
    text: '(Combat): While attacking, this Card gains Armor 1. (Armor decreases any damage received by 1.)\n (Combat): Evasion 1. (Opponents must pay an additional (1) to target this Card.)',
    ccc: 4,
    artist: 'Rafael Lanhellas',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Standard Issue Falchion',
    filename: 'standardissuefalchion',
    id: 109,
    epic: false,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 1,
    power: 2,
    speed: 0,
    text: "Links to a (Combat) non-Epic Unit.\n (Combat): When this Card enters play, recover Linked Unit.\n (Combat): Linked Unit gains the Subtype Soldier.\n (Combat): Linked Unit gains this Card's Pwr.",
    ccc: 6,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Stranger's Fanatic",
    filename: 'strangersfanatic',
    id: 110,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 4,
    pips: [Element.Light, Element.Light, Element.Light],
    hp: 3,
    power: 1,
    speed: 1,
    text: '(Combat): For each (Combat) Cleric you control, this Card gains +1Spd and +1Pwr.\n (Combat): Destroy this Card: Negate target (Stack) Unit.',
    ccc: 3,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Strongarm Thug',
    filename: 'strongarmthug',
    id: 111,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Dark],
    hp: 1,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card deals combat damage to an Enemy Shrine, draw a Card.',
    ccc: 3,
    artist: 'Giraaz Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Sudden Strength',
    filename: 'suddenstrength',
    id: 112,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 3,
    pips: [Element.Earth],
    hp: 0,
    power: 1,
    speed: 1,
    text: "Target (Combat) Unit gains this Card's Spd and Pwr until end of turn. That Unit cannot be destroyed until end of turn.",
    ccc: 1,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Take Root',
    filename: 'takeroot',
    id: 113,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 1,
    pips: [Element.Earth],
    hp: 1,
    power: 0,
    speed: 0,
    text: "Links to a (Combat) Unit.\n (Combat): Linked Unit cannot attack.\n (Combat): Linked Unit's active abilities cannot be used.",
    ccc: 3,
    artist: 'Guillermo Villarreal',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Talia - The Waveshaper',
    filename: 'taliathewaveshaper',
    id: 114,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Craftsman',
    cost: 4,
    pips: [Element.Water, Element.Water],
    hp: 4,
    power: 4,
    speed: 3,
    text: '(Combat): When this Card enters play, return target (Resource) Card you own to your hand. Draw a Card. Place a Card from your hand into your resource zone exhausted.',
    ccc: 0,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Water) >= 0;
    },
  },
  {
    name: 'Targeted Strike',
    filename: 'targetedstrike',
    id: 115,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Fire],
    hp: 0,
    power: 0,
    speed: 1,
    text: 'Target (Combat) Unit you control deals damage equal to its Pwr to target (Combat) Enemy Unit.',
    ccc: 6,
    artist: 'Giraaz Studio',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Temple Dedicant',
    filename: 'templededicant',
    id: 116,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 3,
    pips: [Element.Air],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): Swiftstrike 3. (Swiftstrike increases damage by 3 while in combat with a Unie with less Spd.)',
    ccc: 4,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "Thaddeus's Neophyte",
    filename: 'thaddeussneophyte',
    id: 117,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 3,
    pips: [Element.Light, Element.Light],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, heal 3 damage from target (Combat) Card.',
    ccc: 4,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Thaddeus - Stranger',
    filename: 'thaddeusstranger',
    id: 118,
    epic: true,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 3,
    pips: [Element.Light, Element.Light],
    hp: 5,
    power: 2,
    speed: 1,
    text: '(Combat): (Light)(Exhaust): Heal all damage from another target (Combat) non-Shrine card you control.\n (Combat): (Light)(Light): Recover this Card.',
    ccc: 2,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'The Abyss',
    filename: 'theabyss',
    id: 119,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Assassin',
    cost: 5,
    pips: [Element.Dark, Element.Dark],
    hp: 6,
    power: 3,
    speed: 2,
    text: "(Combat): Lethal. (A Lethal Card's combat damage immediately destroys Units.)\n (Combat): (Dark)(Dark)(Dark): This Card gains +1Spd until end of turn.",
    ccc: 1,
    artist: 'J. C. Grande',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Through the Keyhole',
    filename: 'throughthekeyhole',
    id: 120,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 2,
    pips: [Element.Air, Element.Dark],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Exhaust target (Combat) Unit.\n Target (Combat) Unit gains Stealth 1 until end of turn.',
    ccc: 2,
    artist: 'Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Totem Keeper',
    filename: 'totemkeeper',
    id: 121,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): When you play an Air Event, this Card gains +1Spd and +1Pwr until end of turn.',
    ccc: 4,
    artist: 'Arte Express Studio',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Towerwright',
    filename: 'towerwright',
    id: 122,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Tactician',
    cost: 2,
    pips: [Element.Light, Element.Light],
    hp: 3,
    power: 2,
    speed: 2,
    text: '(Combat): All (Combat) non-Shrine Structures you control gain +1Spd and +1Pwr.',
    ccc: 3,
    artist: 'Glen Fernandez',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Triage',
    filename: 'triage',
    id: 123,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Light],
    hp: 2,
    power: 0,
    speed: 0,
    text: "Heal damage equal to this Card's HP from target (Combat) Unit.\n (Stack): For each (Combat) Cleric you control, this Card gains +1HP.",
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'True Believer',
    filename: 'truebeliever',
    id: 124,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric Warrior',
    cost: 3,
    pips: [Element.Light, Element.Light, Element.Light],
    hp: 5,
    power: 1,
    speed: 2,
    text: '(Combat): Regenerate 4.\n (Combat): Sworn Enemy (Fire), (Air), (Dark): +3Pwr.',
    ccc: 3,
    artist: 'Arte Express Studio',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Underwater Spearman',
    filename: 'underwaterspearman',
    id: 125,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Soldier',
    cost: 2,
    pips: [Element.Water],
    hp: 2,
    power: 2,
    speed: 3,
    text: '(Combat): Waterbound: +1HP. (This Card gains the added text if its Essence is Water.)',
    ccc: 3,
    artist: 'Untung Forevers',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Unseen Duelist',
    filename: 'unseenduelist',
    id: 126,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human',
    cost: 2,
    pips: [Element.Water],
    hp: 2,
    power: 1,
    speed: 3,
    text: '(Combat): Armor 1.\n (Combat): Stealth 1.\n (Combat): Swiftstrike 1.',
    ccc: 1,
    artist: 'Ray of Sand',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Unseen Tactics',
    filename: 'unseentactics',
    id: 127,
    epic: false,
    supertype: BaseCardType.ContinuousEvent,
    subtype: '',
    cost: 3,
    pips: [Element.Water, Element.Water],
    hp: 1,
    power: 0,
    speed: 0,
    text: '(Combat): All (Combat) Units you control gain Pwr equal to their Stealth value.',
    ccc: 3,
    artist: 'John Leo Espiritu',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  // {
  //   name: 'War Kitten',
  //   filename: 'wakittentoken',
  // id: ,
  //   epic: false,
  //   supertype: BaseCardType.Unit,
  //   subtype: 'Cat - Fire',
  //   cost: 0,
  //   pips: [],
  //   hp: 1,
  //   power: 1,
  //   speed: 2,
  //   text: '',
  //   ccc: 0,
  //   artist: 'Megan Toole',
  //   rarity: Rarity.Common,
  //   type: CardType.BaseCard,
  // isValidEssence: (e) => {return true;},
  //},
  {
    name: "War Cat's Mane - Gift of Rage",
    filename: 'warcatsmanegiftofrage',
    id: 128,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Fire, Element.Fire],
    hp: 1,
    power: 4,
    speed: 1,
    text: "Links to a (Combat) Unit you control.\n (Combat): When this Card enters play, exhaust all (Combat) Units if their Pwr is less than this Card's Pwr.\n (Combat): Linked Unit gains Armor equal to this Card's HP and Swiftstrike equal to this Card's Spd.",
    ccc: 2,
    artist: 'Untung Forevers',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return e.id === 68 || e.resources.indexOf(Element.Fire) >= 0;
    },
  },
  {
    name: 'Wardsmith',
    filename: 'wardsmith',
    id: 129,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Craftsman',
    cost: 1,
    pips: [Element.Water],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(Combat): Evasion 4.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Wash Away',
    filename: 'washaway',
    id: 130,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Water],
    hp: 0,
    power: 0,
    speed: 3,
    text: 'Destroy target (Combat) Item.',
    ccc: 3,
    artist: 'Ray of Sand',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Watch Tower',
    filename: 'watchtower',
    id: 131,
    epic: false,
    supertype: BaseCardType.Structure,
    subtype: '',
    cost: 2,
    pips: [Element.Light],
    hp: 4,
    power: 0,
    speed: 0,
    text: '(Combat): All (Combat) Units lose Stealth.',
    ccc: 6,
    artist: 'Isiah Xavier Bradley',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Wave Mender',
    filename: 'wavemender',
    id: 132,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Cleric',
    cost: 3,
    pips: [Element.Light, Element.Water],
    hp: 4,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, heal 1 damage from all (Combat) Cards you control.',
    ccc: 4,
    artist: 'Romar Adriano Olasiman',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Whispers in the Wind',
    filename: 'whispersinthewind',
    id: 133,
    epic: false,
    supertype: BaseCardType.Event,
    subtype: '',
    cost: 1,
    pips: [Element.Air],
    hp: 0,
    power: 0,
    speed: 0,
    text: 'Draw two Cards then discard a Card.',
    ccc: 4,
    artist: 'Megan Toole',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Wind Howler',
    filename: 'windhowler',
    id: 134,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Shaman',
    cost: 4,
    pips: [Element.Air, Element.Air],
    hp: 3,
    power: 2,
    speed: 3,
    text: '(Combat): When this Card enters play, draw a Card.\n (Combat): When this Card enters play, discard any number of Cards. Deal damage equal to the number of Cards discarded this way to all other (Combat) Units.',
    ccc: 1,
    artist: 'Adriano Oliveira & Fernando Cordeiro',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Wind Whisperer',
    filename: 'windwhisperer',
    id: 135,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Shaman',
    cost: 2,
    pips: [Element.Air, Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: '(Combat): When this Card enters play, draw a Card.',
    ccc: 4,
    artist: 'Kayla Raney',
    rarity: Rarity.Common,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Wolf-Heart Shaman',
    filename: 'wolf-heartshaman',
    id: 136,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Shaman',
    cost: 3,
    pips: [Element.Air],
    hp: 2,
    power: 2,
    speed: 2,
    text: "(Combat): When this Card enters play, return target (Combat) Enemy Unit to its owner's hand if its Spd is less than this Card's Spd.",
    ccc: 1,
    artist: 'Untung Forevers',
    rarity: Rarity.Uncommon,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: "X - True King's Sword",
    filename: 'xtruekingssword',
    id: 137,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Earth, Element.Earth],
    hp: 5,
    power: 2,
    speed: 0,
    text: "Links to a (Combat) Unit you control.\n (Combat): If Linked Unit is Earth, it gains the Subtype King and this Card gains +1Spd.\n (Combat): Linked Unit gains this Card's Pwr.\n (Combat): Destroy this Card: Negate Target (Stack) Event.\n (Dead): Use this ability only if you control a (Combat) King; (Earth)(Earth): Return this Card to your hand.",
    ccc: 4,
    artist: 'Domakhin Gleb',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Yawatarara Disciple',
    filename: 'yawataradisciple',
    id: 138,
    epic: false,
    supertype: BaseCardType.Unit,
    subtype: 'Human Warrior',
    cost: 5,
    pips: [Element.Water, Element.Water],
    hp: 4,
    power: 4,
    speed: 2,
    text: '(Combat): When this Card enters play, return target (Dead) Water Event you own to your hand.\n (Combat): When you play a Water Event, this Card gains Stealth 1 until end of turn.',
    ccc: 2,
    artist: 'Untung Forevers',
    rarity: Rarity.Rare,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
  {
    name: 'Zi Tapestry - Esoteric Lore',
    filename: 'zitapestryesotericlore',
    id: 139,
    epic: true,
    supertype: BaseCardType.Item,
    subtype: '',
    cost: 2,
    pips: [Element.Dark],
    hp: 1,
    power: 0,
    speed: 0,
    text: 'Links to a (Combat) Dark Structure you control.\n (Combat): For each damage on Linked Structure, this Card gains +1 Initiative.\n (Combat): (1), Exhaust Linked Structure: Your next action this turn counts as the first action of the turn.',
    ccc: 6,
    artist: 'Arturo Gomez Martinez',
    rarity: Rarity.Epic,
    type: CardType.BaseCard,
    isValidEssence: (e) => {
      return true;
    },
  },
];

export const baseCards: BaseCard[] = uncalculatedBaseCards.map((c) => {
  let m = new Set<number>();
  essences.forEach((e) => {
    if (c.ccc + e.ccc <= 6 && c.isValidEssence(e) && e.isValidBase(c)) {
      m.add(e.id);
    }
  });
  return { ...c, validEssences: m };
});
